### ISSUE TITLE
App is crashing when I'm triggering geolocation plugin in Android 9 and 10

### ISSUE THREAD

**Issue by eaglesiar** [transistorsoft/cordova-background-geolocation-lt#1067]
## Your Environment
* Plugin version: 2.9.1
* Platform:  Android
* OS version: 9, 10
* Device manufacturer / model: All Android devices having Android version> 9
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): cordova-android : 6.4.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

It should work properly
## Actual Behavior
App is crashing when I'm triggering the geolocation plugin

**Comment by christocracy** [comment]
You say it's "crashing" but you provide no evidence?  When a crash occurs, the **first** thing you do is observe the stacktrace in `logcat`.  There is *always* a stacktrace*.

**Comment by eaglesiar** [comment]
Does the version 2.9.1 work with Android 9 and 10 with cordova-android 6.4.0?

**Comment by christocracy** [comment]
>Does the version 2.9.1 work with Android 9 and 10 with cordova-android 6.4.0?

Probably not.  Upgrade the plugin and your cordova to latest.  And **ALWAYS** get your stacktrace from `logcat`

**Comment by eaglesiar** [comment]
║ BackgroundGeolocation Service started
    ╠═════════════════════════════════════════════
2020-01-09 00:16:44.557 6692-6692/com.manh.tms.mobile I/TSLocationManager: [c.t.l.BackgroundGeolocationService d] 
      ✅  Started in foreground
2020-01-09 00:16:44.569 6692-6692/com.manh.tms.mobile D/AndroidRuntime: Shutting down VM
2020-01-09 00:16:44.569 6692-6692/com.manh.tms.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.manh.tms.mobile, PID: 6692
    java.lang.RuntimeException: Unable to start service com.transistorsoft.locationmanager.BackgroundGeolocationService@6899c0d with Intent { cmp=com.manh.tms.mobile/com.transistorsoft.locationmanager.BackgroundGeolocationService (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=6692, uid=10155 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=6692, uid=10155 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6136)
        at android.app.Service.startForeground(Service.java:707)
        at com.transistorsoft.locationmanager.BackgroundGeolocationService.d(Unknown Source:33)
        at com.transistorsoft.locationmanager.BackgroundGeolocationService.onStartCommand(Unknown Source:109)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5928)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1259)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13968)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2784)

**Comment by christocracy** [comment]
Upgrade the plugin, as I said.  This new required permission exists in new versions of the plugin.

java.lang.SecurityException: Permission Denial: startForeground from pid=6692, uid=10155 requires android.permission.FOREGROUND_SERVICE

**Comment by eaglesiar** [comment]
When I upgraded the plugin, it was asking me to upgrade cordova-android >= 7 too. When I upgraded to cordova-android >= 7, app is getting stuck at splashscreen.

**Comment by christocracy** [comment]
Cordova 6.4.0 is **over 3 years old**  Of course you’re going to have issues.  Upgrade all your plugins and view the JavaScript console for errors.

**Comment by eaglesiar** [comment]
(node:88235) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/dhsingh/desktop/TMS/RNDTLMDC/carrier-mobile-ui/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :tslocationmanager:.
  Required by:
      project :app

* Try:

**Comment by christocracy** [comment]
Latest Cordova is 9
https://www.npmjs.com/package/cordova

**Comment by christocracy** [comment]
And whenever you update Cordova, you **ALWAYS** remove / re-add your platforms.
```
$ cordova platform remove android
$ cordova platform add android

$ cordova platform remove ios
$ cordova platform add ios
```
