### ISSUE TITLE
App is crashing in Android 10 due to the plugin

### ISSUE THREAD

**Issue by dhsinghmanh** [transistorsoft/cordova-background-geolocation-lt#1078]
## Your Environment
* Plugin version: 3.4.2
* Platform: Android 
* OS version: Android 10
* Cordova version (`cordova -v`):  8.0.0
* Cordova platform version (`cordova platform ls`):   android 8.1.0
## Expected Behavior
App should work properly
## Actual Behavior
App is crashing

> platforms/android/app/build.gradle

```

apply plugin: 'com.android.application'

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.3'
}

// Configuration properties. Set these via environment variables, build-extras.gradle, or gradle.properties.
// Refer to: http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html
ext {
    apply from: '../CordovaLib/cordova.gradle'

    // The value for android.compileSdkVersion.
    if (!project.hasProperty('cdvCompileSdkVersion')) {
        cdvCompileSdkVersion = null;
    }
    // The value for android.buildToolsVersion.
    if (!project.hasProperty('cdvBuildToolsVersion')) {
        cdvBuildToolsVersion = null;
    }
    // Sets the versionCode to the given value.
    if (!project.hasProperty('cdvVersionCode')) {
        cdvVersionCode = null
    }
    // Sets the minSdkVersion to the given value.
    if (!project.hasProperty('cdvMinSdkVersion')) {
        cdvMinSdkVersion = null
    }
    // Sets the maxSdkVersion to the given value.
    if (!project.hasProperty('cdvMaxSdkVersion')) {
        cdvMaxSdkVersion = null
    }
    // The value for android.targetSdkVersion.
    if (!project.hasProperty('cdvTargetSdkVersion')) {
        cdvTargetSdkVersion = null;
    }
    // Whether to build architecture-specific APKs.
    if (!project.hasProperty('cdvBuildMultipleApks')) {
        cdvBuildMultipleApks = null
    }
    // Whether to append a 0 "abi digit" to versionCode when only a single APK is build
    if (!project.hasProperty('cdvVersionCodeForceAbiDigit')) {
        cdvVersionCodeForceAbiDigit = null
    }
    // .properties files to use for release signing.
    if (!project.hasProperty('cdvReleaseSigningPropertiesFile')) {
        cdvReleaseSigningPropertiesFile = null
    }
    // .properties files to use for debug signing.
    if (!project.hasProperty('cdvDebugSigningPropertiesFile')) {
        cdvDebugSigningPropertiesFile = null
    }
    // Set by build.js script.
    if (!project.hasProperty('cdvBuildArch')) {
        cdvBuildArch = null
    }

    // Plugin gradle extensions can append to this to have code run at the end.
    cdvPluginPostBuildExtras = []
}

// PLUGIN GRADLE EXTENSIONS START
apply from: "../cordova-plugin-background-fetch/mobile-build.gradle"
apply from: "../cordova-background-geolocation-lt/mobile-build.gradle"
apply from: "../cordova-plugin-badge/mobile-badge.gradle"
apply from: "../cordova-plugin-local-notification/mobile-localnotification.gradle"
apply from: "../phonegap-plugin-barcodescanner/mobile-barcodescanner.gradle"
// PLUGIN GRADLE EXTENSIONS END

def hasBuildExtras1 = file('build-extras.gradle').exists()
if (hasBuildExtras1) {
    apply from: 'build-extras.gradle'
}

def hasBuildExtras2 = file('../build-extras.gradle').exists()
if (hasBuildExtras2) {
    apply from: '../build-extras.gradle'
}

// Set property defaults after extension .gradle files.
ext.cdvCompileSdkVersion = cdvCompileSdkVersion == null ? (
    defaultCompileSdkVersion == null 
        ? privateHelpers.getProjectTarget()
        : defaultCompileSdkVersion 
) : Integer.parseInt('' + cdvCompileSdkVersion);

if (ext.cdvBuildToolsVersion == null) {
    ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
    //ext.cdvBuildToolsVersion = project.ext.defaultBuildToolsVersion
}
if (ext.cdvDebugSigningPropertiesFile == null && file('../debug-signing.properties').exists()) {
    ext.cdvDebugSigningPropertiesFile = '../debug-signing.properties'
}
if (ext.cdvReleaseSigningPropertiesFile == null && file('../release-signing.properties').exists()) {
    ext.cdvReleaseSigningPropertiesFile = '../release-signing.properties'
}

// Cast to appropriate types.
ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
ext.cdvVersionCodeForceAbiDigit = cdvVersionCodeForceAbiDigit == null ? false : cdvVersionCodeForceAbiDigit.toBoolean();

// minSdkVersion, maxSdkVersion and targetSdkVersion
ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? defaultMinSdkVersion : Integer.parseInt('' + cdvMinSdkVersion)
if (cdvMaxSdkVersion != null) {
    ext.cdvMaxSdkVersion = Integer.parseInt('' + cdvMaxSdkVersion)
}
ext.cdvTargetSdkVersion = cdvTargetSdkVersion == null ? defaultTargetSdkVersion  : Integer.parseInt('' + cdvTargetSdkVersion)

ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)

def computeBuildTargetName(debugBuild) {
    def ret = 'assemble'
    if (cdvBuildMultipleApks && cdvBuildArch) {
        def arch = cdvBuildArch == 'arm' ? 'armv7' : cdvBuildArch
        ret += '' + arch.toUpperCase().charAt(0) + arch.substring(1);
    }
    return ret + (debugBuild ? 'Debug' : 'Release')
}

// Make cdvBuild a task that depends on the debug/arch-sepecific task.
task cdvBuildDebug
cdvBuildDebug.dependsOn {
    return computeBuildTargetName(true)
}

task cdvBuildRelease
cdvBuildRelease.dependsOn {
    return computeBuildTargetName(false)
}

task cdvPrintProps {
    doLast {
        println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
        println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
        println('cdvVersionCode=' + cdvVersionCode)
        println('cdvVersionCodeForceAbiDigit=' + cdvVersionCodeForceAbiDigit)
        println('cdvMinSdkVersion=' + cdvMinSdkVersion)
        println('cdvMaxSdkVersion=' + cdvMaxSdkVersion)
        println('cdvTargetSdkVersion=' + cdvTargetSdkVersion)
        println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
        println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
        println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
        println('cdvBuildArch=' + cdvBuildArch)
        println('computedVersionCode=' + android.defaultConfig.versionCode)
        android.productFlavors.each { flavor ->
            println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
        }
    }
}

android {
    defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }

        if (cdvMaxSdkVersion != null) {
            maxSdkVersion cdvMaxSdkVersion
        }

        if(cdvTargetSdkVersion != null) {
            targetSdkVersion cdvTargetSdkVersion
        }
    }

    lintOptions {
      abortOnError false;
    }

    compileSdkVersion cdvCompileSdkVersion
    buildToolsVersion cdvBuildToolsVersion

    // This code exists for Crosswalk and other Native APIs.
    // By default, we multiply the existing version code in the
    // Android Manifest by 10 and add a number for each architecture.
    // If you are not using Crosswalk or SQLite, you can
    // ignore this chunk of code, and your version codes will be respected.

    if (Boolean.valueOf(cdvBuildMultipleApks)) {
        flavorDimensions "default"

        productFlavors {
            armeabi {
                versionCode defaultConfig.versionCode*10 + 1
                ndk {
                    abiFilters = ["armeabi"]
                }
            }
            armv7 {
                versionCode defaultConfig.versionCode*10 + 2
                ndk {
                    abiFilters = ["armeabi-v7a"]
                }
            }
            arm64 {
                versionCode defaultConfig.versionCode*10 + 3
                ndk {
                    abiFilters = ["arm64-v8a"]
                }
            }
            x86 {
                versionCode defaultConfig.versionCode*10 + 4
                ndk {
                    abiFilters = ["x86"]
                }
            }
            x86_64 {
                versionCode defaultConfig.versionCode*10 + 5
                ndk {
                    abiFilters = ["x86_64"]
                }
            }
        }
    } else if (Boolean.valueOf(cdvVersionCodeForceAbiDigit)) {
        // This provides compatibility to the default logic for versionCode before cordova-android 5.2.0
        defaultConfig {
            versionCode defaultConfig.versionCode*10
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    if (cdvReleaseSigningPropertiesFile) {
        signingConfigs {
            release {
                // These must be set or Gradle will complain (even if they are overridden).
                keyAlias = ""
                keyPassword = "__unset" // And these must be set to non-empty in order to have the signing step added to the task graph.
                storeFile = null
                storePassword = "__unset"
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
        addSigningProps(cdvReleaseSigningPropertiesFile, signingConfigs.release)
    }

    if (cdvDebugSigningPropertiesFile) {
        addSigningProps(cdvDebugSigningPropertiesFile, signingConfigs.debug)
    }
}

/*
 * WARNING: Cordova Lib and platform scripts do management inside of this code here,
 * if you are adding the dependencies manually, do so outside the comments, otherwise
 * the Cordova tools will overwrite them
 */


dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "com.google.android.gms:play-services-location:11.6.0"
    implementation "com.android.support:appcompat-v7:26.1.0"
    implementation "com.squareup.okhttp3:okhttp:3.12.+"
    implementation "org.greenrobot:eventbus:3.0.0"
    implementation "com.intentfilter:android-permissions:0.1.8"
    implementation "org.slf4j:slf4j-api:1.7.25"
    implementation "com.github.tony19:logback-android:2.0.0"
    implementation "com.android.support:support-v4:24.1.1+"
    implementation "com.android.support:support-v4:26.+"
    implementation "com.android.support:support-v4:27.+"
    implementation "com.android.support:appcompat-v7:27.+"
    // SUB-PROJECT DEPENDENCIES END
}

def promptForReleaseKeyPassword() {
    if (!cdvReleaseSigningPropertiesFile) {
        return;
    }
    if ('__unset'.equals(android.signingConfigs.release.storePassword)) {
        android.signingConfigs.release.storePassword = privateHelpers.promptForPassword('Enter key store password: ')
    }
    if ('__unset'.equals(android.signingConfigs.release.keyPassword)) {
        android.signingConfigs.release.keyPassword = privateHelpers.promptForPassword('Enter key password: ');
    }
}

gradle.taskGraph.whenReady { taskGraph ->
    taskGraph.getAllTasks().each() { task ->
      if(['validateReleaseSigning', 'validateSigningRelease', 'validateSigningArmv7Release', 'validateSigningX76Release'].contains(task.name)) {
         promptForReleaseKeyPassword()
      }
    }
}

def addSigningProps(propsFilePath, signingConfig) {
    def propsFile = file(propsFilePath)
    def props = new Properties()
    propsFile.withReader { reader ->
        props.load(reader)
    }

    def storeFile = new File(props.get('key.store') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'storeFile'))
    if (!storeFile.isAbsolute()) {
        storeFile = RelativePath.parse(true, storeFile.toString()).getFile(propsFile.getParentFile())
    }
    if (!storeFile.exists()) {
        throw new FileNotFoundException('Keystore file does not exist: ' + storeFile.getAbsolutePath())
    }
    signingConfig.keyAlias = props.get('key.alias') ?: privateHelpers.ensureValueExists(propsFilePath, props, 'keyAlias')
    signingConfig.keyPassword = props.get('keyPassword', props.get('key.alias.password', signingConfig.keyPassword))
    signingConfig.storeFile = storeFile
    signingConfig.storePassword = props.get('storePassword', props.get('key.store.password', signingConfig.storePassword))
    def storeType = props.get('storeType', props.get('key.store.type', ''))
    if (!storeType) {
        def filename = storeFile.getName().toLowerCase();
        if (filename.endsWith('.p12') || filename.endsWith('.pfx')) {
            storeType = 'pkcs12'
        } else {
            storeType = signingConfig.storeType // "jks"
        }
    }
    signingConfig.storeType = storeType
}

for (def func : cdvPluginPostBuildExtras) {
    func()
}

// This can be defined within build-extras.gradle as:
//     ext.postBuildExtras = { ... code here ... }
if (hasProperty('postBuildExtras')) {
    postBuildExtras()
}
```

> platforms/android/build.gradle
```

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }

    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="28.0.3" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=28 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=28 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

## Debug logs

<details>
	<summary>Logs</summary>
2020-01-20 21:20:45.203 18003-18112/com.mycom.app.mobile W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;
2020-01-20 21:20:45.203 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
2020-01-20 21:20:45.203 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.reflect.Method.getParameterTypes(Method.java:186)
2020-01-20 21:20:45.203 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
2020-01-20 21:20:45.203 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:171)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:17)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:1172)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:126)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:109)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
2020-01-20 21:20:45.204 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.Looper.loop(Looper.java:174)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityTransitionEvent" on path: DexPathList[[zip file "/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/lib/x86, /data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-01-20 21:20:45.205 18003-18112/com.mycom.app.mobile W/System.err: 	... 21 more
2020-01-20 21:20:45.214 18003-18119/com.mycom.app.mobile E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.mycom.app.mobile, PID: 18003
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;
        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
        at java.lang.reflect.Method.getParameterTypes(Method.java:186)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:171)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:15)
        at com.transistorsoft.locationmanager.adapter.TSConfig$a.a(Unknown Source:15)
        at com.transistorsoft.locationmanager.adapter.TSConfig$a.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityTransitionEvent" on path: DexPathList[[zip file "/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/lib/x86, /data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:186) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:171) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:15) 
        at com.transistorsoft.locationmanager.adapter.TSConfig$a.a(Unknown Source:15) 
        at com.transistorsoft.locationmanager.adapter.TSConfig$a.doInBackground(Unknown Source:2) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-01-20 21:20:45.217 18003-18112/com.mycom.app.mobile W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;
2020-01-20 21:20:45.218 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
2020-01-20 21:20:45.218 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.reflect.Method.getParameterTypes(Method.java:186)
2020-01-20 21:20:45.219 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
2020-01-20 21:20:45.220 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
2020-01-20 21:20:45.220 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
2020-01-20 21:20:45.220 18003-18112/com.mycom.app.mobile W/System.err:     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
2020-01-20 21:20:45.220 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:171)
2020-01-20 21:20:45.221 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
2020-01-20 21:20:45.222 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:17)
2020-01-20 21:20:45.222 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:1172)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:126)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:109)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.Looper.loop(Looper.java:174)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityTransitionEvent" on path: DexPathList[[zip file "/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/lib/x86, /data/app/com.mycom.app.mobile-GSrQh4eLZPRktCpJvHQAQQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-01-20 21:20:45.223 18003-18112/com.mycom.app.mobile W/System.err: 	... 21 more
2020-01-20 21:20:45.228 18003-18003/com.mycom.app.mobile D/CordovaActivity: Paused the activity.
2020-01-20 21:20:45.229 18003-18119/com.mycom.app.mobile I/Process: Sending signal. PID: 18003 SIG: 9

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent

You're using *too low* a version of `play-services:location`.
>implementation "com.google.android.gms:play-services-location:11.6.0"

The latest non-androidX version of `play-services:location` is `16.0.0`.  [`11.6.0` is over 2 years old](https://developers.google.com/android/guides/releases).  You should strive to always use the latest available Google APIs.

**Comment by dhsinghmanh** [comment]
How to upgrade it in the code? I'm using the paid version of the plugin. Is there any way to communicate with you in chat?

**Comment by christocracy** [comment]
The plugin controls its version of `play-services:location` via [this](https://github.com/transistorsoft/cordova-background-geolocation-lt#variable-google_api_version-16)

**Comment by dhsinghmanh** [comment]
Now I'm getting this.


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mycom.app.mobile , PID: 20951
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(channel=com.manh.tms.mobileTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by christocracy** [comment]
Your gradle file *is a complete mess*.  Is this a Capacitor app?

```
implementation "com.android.support:support-v4:24.1.1+"
    implementation "com.android.support:support-v4:26.+"
    implementation "com.android.support:support-v4:27.+"
    implementation "com.android.support:appcompat-v7:27.+"
```

You have 3 different versions of `com.android.support` dependencies.  They're all supposed to be the same and correspond to your `defaultCompileSdkVersion=28`.

This is not my responsibility.
