### ISSUE TITLE
Exiting Version plugin remove not working , platform remove also not working.

### ISSUE THREAD

**Issue by paulatrockhill** [transistorsoft/cordova-background-geolocation-lt#1122]
## Your Environment
* Plugin version:

cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

* Platform: iOS and Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE

D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA>ionic cordova plugin remove cordova-background-geolocation-lt
> cordova.cmd plugin remove cordova-background-geolocation-lt
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-background-fetch from android
Error during processing of action! Attempting to revert...
Uh oh!
EPERM: operation not permitted, rmdir 'D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA\platforms\android\app\src\main\java\com\transistorsoft\cordova\backgroundfetch'

D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA>ionic cordova platform rm android
> cordova.cmd platform remove android
Removing android from cordova.platforms array in package.json
Error: npm: Command failed with exit code 4294963248 Error output:
npm WARN @angular/compiler-cli@5.2.11 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.27.5 requires a peer of typescript@>=2.4.2 <2.8 but none is installed. You must install peer dependencies yourself.

npm ERR! code EPERM
npm ERR! syscall rmdir
npm ERR! path D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA\node_modules\android-versions\tests
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rmdir 'D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA\node_modules\android-versions\tests'
npm ERR!  [OperationalError: EPERM: operation not permitted, rmdir 'D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA\node_modules\android-versions\tests'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rmdir 'D:\Cordova Projects\LiveIonicProjects\SmartTrackAppA\node_modules\android-versions\tests'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rmdir',
npm ERR!     path: 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, rmdir 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests',
npm ERR!   parent: 'SmartTrackAppA'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rengarajan Perumal\AppData\Roaming\npm-cache\_logs\2020-05-01T12_20_24_805Z-debug.log
    at ChildProcess.whenDone (C:\Users\Rengarajan Perumal\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\superspawn.js:135:23)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.cp.emit (C:\Users\Rengarajan Perumal\AppData\Roaming\npm\node_modules\cordova\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  stderr: 'npm WARN @angular/compiler-cli@5.2.11 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.\n' +
    'npm WARN tsickle@0.27.5 requires a peer of typescript@>=2.4.2 <2.8 but none is installed. You must install peer dependencies yourself.\n' +
    '\n' +
    'npm ERR! code EPERM\n' +
    'npm ERR! syscall rmdir\n' +
    'npm ERR! path D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests\n' +
    'npm ERR! errno -4048\n' +
    "npm ERR! Error: EPERM: operation not permitted, rmdir 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests'\n" +
    "npm ERR!  [OperationalError: EPERM: operation not permitted, rmdir 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests'] {\n" +
    "npm ERR!   cause: [Error: EPERM: operation not permitted, rmdir 'D:\\Cordova Projects\\LiveIonicProjects\\SmartTrackAppA\\node_modules\\android-versions\\tests'] {\n" +
    'npm ERR!     errno: -4048,\n' +
    "npm ERR!     code: 'EPERM',\n" +
    "npm ERR!     syscall: 'rmdir',\n" +
    "npm ERR!     path: 'D:\\\\Cordova Projects\\\\LiveIonicProjects\\\\SmartTrackAppA\\\\node_modules\\\\android-versions\\\\tests'\n" +
    'npm ERR!   },\n' +
    `npm ERR!   stack: "Error: EPERM: operation not permitted, rmdir 'D:\\\\Cordova Projects\\\\LiveIonicProjects\\\\SmartTrackAppA\\\\node_modules\\\\android-versions\\\\tests'",\n` +
    'npm ERR!   errno: -4048,\n' +
    "npm ERR!   code: 'EPERM',\n" +
    "npm ERR!   syscall: 'rmdir',\n" +
    "npm ERR!   path: 'D:\\\\Cordova Projects\\\\LiveIonicProjects\\\\SmartTrackAppA\\\\node_modules\\\\android-versions\\\\tests',\n" +
    "npm ERR!   parent: 'SmartTrackAppA'\n" +
    'npm ERR! }\n' +
    'npm ERR! \n' +
    'npm ERR! The operation was rejected by your operating system.\n' +
    "npm ERR! It's possible that the file was already in use (by a text editor or antivirus),\n" +
    'npm ERR! or that you lack permissions to access it.\n' +
    'npm ERR! \n' +
    'npm ERR! If you believe this might be a permissions issue, please double-check the\n' +
    'npm ERR! permissions of the file and its containing directories, or try running\n' +
    'npm ERR! the command again as root/Administrator.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\Rengarajan Perumal\\AppData\\Roaming\\npm-cache\\_logs\\2020-05-01T12_20_24_805Z-debug.log\n',
  code: 4294963248
}
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform remove android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

```

## Expected Behavior
we want remove existing plugin  and need new version plugin , we need to 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
> The operation was rejected by your operating system.

This is not an issue with the plugin.  Search the error in the context of “Cordova”
