### ISSUE TITLE
App crashes on start with combination of capacitor, and appflow deploy with complaint of Cordova-Whitelist plugin

### ISSUE THREAD

**Issue by soleary1222** [transistorsoft/cordova-background-geolocation-lt#1123]
## Your Environment
* Plugin version: 3.6.3
* Platform: iOS or Android - Android
* OS version: 8.0
* Device manufacturer / model: Samsung Galaxy s7
* Cordova version (`cordova -v`):  9.0.0
* Cordova platform version (`cordova platform ls`): 
  android ^8.0.0
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
INSERT_YOUR_CODE_HERE
```

## Expected Behavior

App should not crash for capacitor build.

## Actual Behavior

It is possible that I was able to get a version of this working when I wasn't doing an appflow live deploy, but I couldn't reproduce that later on.
Also, the crash complains about the whitelist plugin, but it is there.  If I remove cordova-background-geolocation-lt, then my build works without a crash.

## Steps to Reproduce

1. Create a new ionic capacitor app
2. Setup ionic appflow(?) - I'm doing this but not sure if it contributes to the problem (ionic link, ionic deploy add)
3. npx cap sync android 
4. Ensure that cordova-whitelist plugin is included in android/app/src/main/res/xml/config.xml
5. Build for Android in debug mode
6. Install apk on device
7. Crash when opens 

## Context
Start the app

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->

05-04 17:04:29.577 10373 30016 30016 D Capacitor: Starting BridgeActivity
05-04 17:04:29.585 10373 30016 30016 W System.err: java.lang.ClassNotFoundException: org.apache.cordova.whitelist.WhitelistPlugin
05-04 17:04:29.585 10373 30016 30016 W System.err: at java.lang.Class.classForName(Native Method)
05-04 17:04:29.585 10373 30016 30016 W System.err: at java.lang.Class.forName(Class.java:453)
05-04 17:04:29.585 10373 30016 30016 W System.err: at java.lang.Class.forName(Class.java:378)
05-04 17:04:29.585 10373 30016 30016 W System.err: at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
05-04 17:04:29.585 10373 30016 30016 W System.err: at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
05-04 17:04:29.586 10373 30016 30016 W System.err: at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
05-04 17:04:29.586 10373 30016 30016 W System.err: at org.apache.cordova.PluginManager.init(PluginManager.java:86)
05-04 17:04:29.586 10373 30016 30016 W System.err: at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:62)
05-04 17:04:29.586 10373 30016 30016 W System.err: at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:75)
05-04 17:04:29.586 10373 30016 30016 W System.err: at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:58)
05-04 17:04:29.586 10373 30016 30016 W System.err: at com.perdiem.usegale.MainActivity.onCreate(MainActivity.java:16)
05-04 17:04:29.586 10373 30016 30016 W System.err: at android.app.Activity.performCreate(Activity.java:7183)
05-04 17:04:29.586 10373 30016 30016 W System.err: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.os.Handler.dispatchMessage(Handler.java:105)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.os.Looper.loop(Looper.java:164)
05-04 17:04:29.587 10373 30016 30016 W System.err: at android.app.ActivityThread.main(ActivityThread.java:6944)
05-04 17:04:29.587 10373 30016 30016 W System.err: at java.lang.reflect.Method.invoke(Native Method)
05-04 17:04:29.587 10373 30016 30016 W System.err: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-04 17:04:29.588 10373 30016 30016 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
05-04 17:04:29.588 10373 30016 30016 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.cordova.whitelist.WhitelistPlugin" on path: DexPathList[[zip file "/data/app/com.perdiem.gale-2P77ExkNdUtwqmTcLdmyWw==/base.apk"],nativeLibraryDirectories=[/data/app/com.perdiem.gale-2P77ExkNdUtwqmTcLdmyWw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
05-04 17:04:29.588 10373 30016 30016 W System.err: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
05-04 17:04:29.588 10373 30016 30016 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-04 17:04:29.588 10373 30016 30016 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-04 17:04:29.588 10373 30016 30016 W System.err: ... 23 more
05-04 17:04:29.589 10373 30016 30016 I System.out: Error adding plugin org.apache.cordova.whitelist.WhitelistPlugin.
05-04 17:04:29.589 10373 30016 30016 D AndroidRuntime: Shutting down VM
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: FATAL EXCEPTION: main
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: Process: com.perdiem.gale, PID: 30016
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.perdiem.gale/com.perdiem.usegale.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:105)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6944)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at org.apache.cordova.PluginManager.init(PluginManager.java:86)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:62)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:75)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:58)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at com.perdiem.usegale.MainActivity.onCreate(MainActivity.java:16)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7183)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
05-04 17:04:29.592 10373 30016 30016 E AndroidRuntime: ... 9 more
```
This is my config.xml file:
```<?xml version='1.0' encoding='utf-8'?>
<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <access origin="*" />

  <feature name="IonicCordovaCommon">
    <param name="android-package" value="com.ionicframework.common.IonicCordovaCommon" onload="true"/>
  </feature>

  <feature name="Whitelist">
    <param name="android-package" value="org.apache.cordova.whitelist.WhitelistPlugin"/>
    <param name="onload" value="true"/>
  </feature>

  <feature name="Sms">
    <param name="android-package" value="com.cordova.plugins.sms.Sms"/>
  </feature>

  <feature name="SQLitePlugin">
    <param name="android-package" value="io.sqlc.SQLitePlugin"/>
  </feature>

  <feature name="OneSignalPush">
    <param name="android-package" value="com.plugin.gcm.OneSignalPush"/>
  </feature>
  
  <feature name="BackgroundGeolocation">
    <param name="android-package" value="com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation"/>
  </feature>

  <feature name="BackgroundFetch">
    <param name="android-package" value="com.transistorsoft.cordova.backgroundfetch.CDVBackgroundFetch"/>
  </feature>
  
</widget>
```

This is my capacitor.build.gradle
```
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN

android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
  }
}

apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
dependencies {

    implementation "com.google.android.gms:play-services-location:16.+"
    implementation "com.android.support:appcompat-v7:28.+"
    implementation "com.squareup.okhttp3:okhttp:3.12.+"
    implementation "org.greenrobot:eventbus:3.0.0"
    implementation "com.intentfilter:android-permissions:0.1.8"
    implementation "org.slf4j:slf4j-api:1.7.25"
    implementation "com.github.tony19:logback-android:2.0.0"
    implementation "com.onesignal:OneSignal:3.13.1"
}
apply from: "../../node_modules/cordova-background-geolocation-lt/src/android/build.gradle"
apply from: "../../node_modules/cordova-plugin-background-fetch/src/android/build.gradle"
apply from: "../../node_modules/cordova-plugin-ionic/src/android/cordovapluginionic.gradle"
apply from: "../../node_modules/onesignal-cordova-plugin/build-extras-onesignal.gradle"

if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}

```
and finally my build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.perdiem.gale"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 50
        versionName "2.80"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions { 
        checkReleaseBuilds false 
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
}

apply from: 'capacitor.build.gradle'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}
```
</details>

**Comment by christocracy** [comment]
This plugin doesn’t reference whitelist as a dependency.  Maybe you need to add it.

I suggest you create a simple hello world Capacitor project and see if you can reproduce the issue.

**Comment by soleary1222** [comment]
It turns out that cordova-plugin-ionic has a dependency for cordova-plugin-whitelist.  The cordova-plugin-ionic is used for the appflow live deploy/update feature.  

It appears that cordova-plugin-ionic and cordova-background-geolocation-lt are incompatible.  If I remove one or the other, everything works fine.  With both together my app crashes.

**Comment by christocracy** [comment]
You’re making a capacitor app.  You don’t need cordova-plugin-ionic

**Comment by soleary1222** [comment]
cordova-plugin-ionic is added as part of the appflow feature of ionic whether or not it is capacitor: https://ionicframework.com/blog/introducing-capacitor-support-for-ionic-appflow/

I created a hello world app like so:
1. New ionic capacitor project following the instructions here: https://capacitor.ionicframework.com/docs/getting-started/with-ionic/
`ionic start myApp tabs --capacitor`
`ionic build`
`npx cap add android`

2. Create a git repo for the project

3. Using the instructions here I add the AppFloe feature: https://ionicframework.com/blog/introducing-capacitor-support-for-ionic-appflow/
`ionic link`
`ionic deploy add`

4. Set gradlew permissions for build:
`cd android`
`git update-index --chmod=+x gradlew`

5. Update version of gradle being used in build.gradle (root)
` classpath 'com.android.tools.build:gradle:3.6.3'`  (vs 3.6.1)

6. Committed code for build and downloaded apk from https://dashboard.ionicframework.com/

7. Tested on device and verified that it does not crash

8. Install cordova-background-geolocation-lt per here: https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/help/INSTALL_CAPACITOR.md
`npm install cordova-background-geolocation-lt`
`npx cap sync`
(Then added lines to build.gradle per instructions)

9. Commit to AppFlow

10. Build fails with: 
* What went wrong:
A problem occurred evaluating project ':capacitor-cordova-android-plugins'.
Could not get unknown property 'applicationVariants' for object of type com.android.build.gradle.LibraryExtension.

![image](https://user-images.githubusercontent.com/6031711/81096998-3b29e100-8ed5-11ea-87ef-277716d81132.png)

**Comment by soleary1222** [comment]
Any thoughts on this?

**Comment by christocracy** [comment]
Did you [see this](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#363---2020-04-15)

**Comment by soleary1222** [comment]
Yes as I mentioned in the above post in step 8, I followed the android instructions on that screen

**Comment by christocracy** [comment]
Please make a new *Hello World* project that reproduces the issue and share that repo with me.

**Comment by soleary1222** [comment]
Thanks @christocracy - I have invited you to the hello world repo here (but it's also public): https://github.com/soleary1222/helloworld-background-geolocation

**Comment by soleary1222** [comment]
Here's more details on the debug build of this - maybe somehow it's not recognizing capacitor correctly?

![Annotation 2020-05-12 140225](https://user-images.githubusercontent.com/6031711/81729046-5a86b800-9459-11ea-9735-caf89118299e.png)

**Comment by soleary1222** [comment]
On node_modules\cordova-background-geolocation-lt\src\android\build.gradle
on line 3...
Would it work to change this...
```def userDir = System.getProperty("user.dir")```
to something like this...?
```def userDir = "${projectDir}/../../"```

**Comment by soleary1222** [comment]
#1128 fixed this issue for me
