### ISSUE TITLE
App Crashing on Startup

### ISSUE THREAD

**Issue by ggiordan** [transistorsoft/cordova-background-geolocation-lt#1266]
## Your Environment
* Plugin version: 4.0.1
* Platform: iOS or Android: Android
* OS version: 11
* Device manufacturer / model:  Pixel 4
* Cordova version (`cordova -v`): 10.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config provided to `#ready`: (I cut and paste the sample code)
```javascript <!-- syntax-highlighting:  paste your code below -->
               // 2. Execute #ready method:
                bgGeo.ready({
                  reset: true,
                  debug: true,
                  logLevel: bgGeo.LOG_LEVEL_VERBOSE,
                  desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                  distanceFilter: 10,
                  url: 'http://my.server.com/locations',
                  autoSync: true,
                  stopOnTerminate: false,
                  startOnBoot: true
                }, function(state) {    // <-- Current state provided to #configure callback
                  // 3.  Start tracking
                  console.log('BackgroundGeolocation is configured and ready to use');
                  if (!state.enabled) {
                    bgGeo.start().then(function() {
                      console.log('- BackgroundGeolocation tracking started');
                    });
                  }
                });
```

## Expected Behavior
Application to start normally and for the "BackgroundGeolocation is configured and ready to use" to show in the log.

## Actual Behavior
Application seems to die, the window closes and I get an 'app keeps stopping' message.
I do see another process get started, I see the license tombstone message AFTER the app crashes.

Logcat has the following:
```
2021-05-12 18:51:46.250 4929-4929/com.trumsoft.rovermobilegap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trumsoft.rovermobilegap, PID: 4929
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

When I run in the emulator, I get a slightly different exception:
```<!-- Syntax highlighting:  DO NOT REMOVE -->
    ╔═════════════════════════════════════════════
    ║ TSLocationManager version: 3.1.22 (378)
    ╠═════════════════════════════════════════════
    ╟─ Google Android SDK built for x86 @ 10 (cordova)

2021-05-12 18:54:27.462 8094-8094/com.trumsoft.rovermobilegap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trumsoft.rovermobilegap, PID: 8094
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=com.trumsoft.rovermobilegapTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Steps to Reproduce

1. start the app

## Context
Simply initialize the plugin, just added the sample code to my onDeviceReady.

From my build.gradle: (I saw the discussions about mixed versions, I think I'm good here)
```
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "com.android.support:support-v13:28.0.0"
    implementation "me.leolin:ShortcutBadger:1.1.17@aar"
    implementation "com.google.firebase:firebase-messaging:18.+"
    implementation "com.google.android.gms:play-services-location:16.+"
    implementation "com.android.support:appcompat-v7:28.+"
    implementation "com.squareup.okhttp3:okhttp:3.12.+"
    implementation "org.greenrobot:eventbus:3.0.0"
    implementation "com.intentfilter:android-permissions:0.1.8"
    implementation "org.slf4j:slf4j-api:1.7.25"
    implementation "com.github.tony19:logback-android:2.0.0"
    // SUB-PROJECT DEPENDENCIES END
```

These are the plugins in use:
```
@havesource/cordova-plugin-push 2.0.0 "Cordova Push Plugin"
cordova-androidx-build 1.0.4 "cordova-androidx-build"
cordova-background-geolocation-lt 4.0.1 "BackgroundGeolocation"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 7.0.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.8.0-20200709-2008 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ios-non-exempt-encryption 1.0.0 "ITSAppUsesNonExemptEncryption false"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-file-xhr 3.0.0 "Cordova WKWebView File XHR Plugin"
```
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
2021-05-12 18:54:26.508 8094-8094/? I/.rovermobilega: Not late-enabling -Xcheck:jni (already on)
2021-05-12 18:54:26.535 8094-8094/? E/.rovermobilega: Unknown bits set in runtime_flags: 0x8000
2021-05-12 18:54:26.536 8094-8094/? W/.rovermobilega: Unexpected CPU variant for X86 using defaults: x86
2021-05-12 18:54:26.669 8094-8094/com.trumsoft.rovermobilegap I/.rovermobilega: The ClassLoaderContext is a special shared library.
2021-05-12 18:54:27.116 8094-8094/com.trumsoft.rovermobilegap D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
2021-05-12 18:54:27.116 8094-8094/com.trumsoft.rovermobilegap D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
2021-05-12 18:54:27.117 8094-8094/com.trumsoft.rovermobilegap D/FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
2021-05-12 18:54:27.117 8094-8094/com.trumsoft.rovermobilegap I/FirebaseInitProvider: FirebaseApp initialization successful
2021-05-12 18:54:27.265 8094-8094/com.trumsoft.rovermobilegap W/.rovermobilega: Accessing hidden method Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application; (greylist, reflection, allowed)
2021-05-12 18:54:27.306 8094-8094/com.trumsoft.rovermobilegap E/TSLocationManager: ╔═════════════════════════════════════════════
    ║ LICENSE VALIDATION FAILURE: com.trumsoft.rovermobilegap
    ╠═════════════════════════════════════════════
    ╟─ Invalid license key: YOUR_LICENSE_KEY_HERE
    ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
    ╚═════════════════════════════════════════════
2021-05-12 18:54:27.361 8094-8094/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
    ╔═════════════════════════════════════════════
    ║ TSLocationManager version: 3.1.22 (378)
    ╠═════════════════════════════════════════════
    ╟─ Google Android SDK built for x86 @ 10 (cordova)
    {
      "activityRecognitionInterval": 10000,
      "allowIdenticalLocations": false,
      "authorization": {},
      "autoSync": true,
      "autoSyncThreshold": 0,
      "backgroundPermissionRationale": {
        "title": "Allow {applicationName} to access this device's location even when closed or not in use?",
        "message": "[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.",
        "positiveAction": "Change to \"{backgroundPermissionOptionLabel}\"",
        "negativeAction": ""
      },
      "batchSync": false,
      "configUrl": "",
      "debug": true,
      "deferTime": 0,
      "desiredAccuracy": -1,
      "desiredOdometerAccuracy": 100,
      "disableAutoSyncOnCellular": false,
      "disableElasticity": false,
      "disableLocationAuthorizationAlert": false,
      "disableMotionActivityUpdates": false,
      "disableStopDetection": false,
      "distanceFilter": 10,
      "elasticityMultiplier": 1,
      "enableHeadless": false,
      "enableTimestampMeta": false,
      "extras": {},
      "fastestLocationUpdateInterval": -1,
      "foregroundService": true,
      "geofenceInitialTriggerEntry": true,
      "geofenceModeHighAccuracy": false,
      "geofenceProximityRadius": 1000,
      "geofenceTemplate": "",
      "headers": {},
      "headlessJobService": "com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask",
      "heartbeatInterval": -1,
      "httpRootProperty": "location",
      "httpTimeout": 60000,
      "isMoving": false,
      "locationAuthorizationRequest": "Always",
      "locationTemplate": "",
      "locationTimeout": 60,
      "locationUpdateInterval": 1000,
      "locationsOrderDirection": "ASC",
      "logLevel": 5,
      "logMaxDays": 3,
      "maxBatchSize": -1,
      "maxDaysToPersist": 1,
      "maxRecordsToPersist": -1,
      "method": "POST",
      "minimumActivityRecognitionConfidence": 75,
      "motionTriggerDelay": 0,
      "notification": {
        "layout": "",
        "title": "",
        "text": "Location Service activated",
        "color": "",
        "channelName": "TSLocationManager",
        "smallIcon": "",
        "largeIcon": "",
        "priority": 0,
        "sticky": false,
        "strings": {},
        "actions": []
      },
      "params": {},
      "persist": true,
      "persistMode": 2,
      "schedule": [],
      "scheduleUseAlarmManager": false,
      "speedJumpFilter": 300,
      "startOnBoot": true,
      "stationaryRadius": 25,
      "stopAfterElapsedMinutes": 0,
      "stopOnStationary": false,
      "stopOnTerminate": false,
      "stopTimeout": 5,
      "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
      "url": "http:\/\/my.server.com\/locations",
      "useSignificantChangesOnly": false,
      "enabled": true,
      "schedulerEnabled": false,
      "trackingMode": 1,
      "odometer": 0,
      "isFirstBoot": false,
      "didLaunchInBackground": false
    }
2021-05-12 18:54:27.376 8094-8094/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.adapter.TSConfig print] 
    ╔═════════════════════════════════════════════
    ║ DEVICE SENSORS
    ╠═════════════════════════════════════════════
    ╟─ ✅  ACCELEROMETER: {Sensor name="Goldfish 3-axis Accelerometer", vendor="The Android Open Source Project", version=1, type=1, maxRange=39.3, resolution=2.480159E-4, power=3.0, minDelay=10000}
    ╟─ ✅  GYROSCOPE: {Sensor name="Goldfish 3-axis Gyroscope", vendor="The Android Open Source Project", version=1, type=4, maxRange=16.46, resolution=0.001, power=3.0, minDelay=10000}
    ╟─ ✅  MAGNETOMETER: {Sensor name="Goldfish 3-axis Magnetic field sensor", vendor="The Android Open Source Project", version=1, type=2, maxRange=2000.0, resolution=0.5, power=6.7, minDelay=10000}
    ╟─ ⚠️  SIGNIFICANT_MOTION:  none.  Motion-detection system performance will be degraded
    ╚═════════════════════════════════════════════
2021-05-12 18:54:27.397 8094-8094/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] 
      🎾  LocationRequestService [eventCount: 1]
2021-05-12 18:54:27.407 8094-8129/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
      ✅  Google Play Services: connected (version code:12451000)
2021-05-12 18:54:27.421 8094-8094/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] 
      🎾  LocationRequestService [eventCount: 2]
2021-05-12 18:54:27.436 8094-8136/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.s.LocationRequestService b] 
    ╔═════════════════════════════════════════════
    ║ getCurrentPosition LocationResult: 1
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 37.421998,-122.084000 hAcc=20 et=+1h49m2s511ms alt=5.0 vel=0.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1690ms, time: 1620860064000
2021-05-12 18:54:27.439 8094-8136/com.trumsoft.rovermobilegap W/TSLocationManager: [c.t.l.s.LocationRequestService b] 
      ⚠️  Failed to find SingleLocationRequest: 1
2021-05-12 18:54:27.441 8094-8094/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] 
      🎾  LocationRequestService [eventCount: 3]
2021-05-12 18:54:27.444 8094-8140/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.s.LocationRequestService a] 
      ℹ️  Location availability: true
2021-05-12 18:54:27.455 8094-8140/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 2, sticky: true]
2021-05-12 18:54:27.461 8094-8094/com.trumsoft.rovermobilegap D/AndroidRuntime: Shutting down VM
2021-05-12 18:54:27.462 8094-8094/com.trumsoft.rovermobilegap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.trumsoft.rovermobilegap, PID: 8094
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=com.trumsoft.rovermobilegapTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-05-12 18:54:27.463 8094-8146/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.s.LocationRequestService b] 
    ╔═════════════════════════════════════════════
    ║ getCurrentPosition LocationResult: 1
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 37.421998,-122.084000 hAcc=20 et=+1h49m2s795ms alt=5.0 vel=0.0 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1433ms, time: 1620860065000
2021-05-12 18:54:27.464 8094-8146/com.trumsoft.rovermobilegap W/TSLocationManager: [c.t.l.s.LocationRequestService b] 
      ⚠️  Failed to find SingleLocationRequest: 1
2021-05-12 18:54:27.524 8094-8136/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
2021-05-12 18:54:27.524 8094-8146/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
2021-05-12 18:54:27.524 8094-8129/com.trumsoft.rovermobilegap D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-05-12 18:54:27.541 8094-8129/com.trumsoft.rovermobilegap W/.rovermobilega: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
2021-05-12 18:54:27.541 8094-8129/com.trumsoft.rovermobilegap W/.rovermobilega: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
2021-05-12 18:54:27.541 8094-8129/com.trumsoft.rovermobilegap W/.rovermobilega: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
2021-05-12 18:54:27.574 8094-8129/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
      🎾  Start monitoring connectivity changes
2021-05-12 18:54:27.595 8094-8151/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.http.HttpService a] 
    ╔═════════════════════════════════════════════
    ║ 📶  Connectivity change: connected? true
    ╠═════════════════════════════════════════════
2021-05-12 18:54:27.600 8094-8129/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.a.BackgroundGeolocation d] 
      🎾  Start monitoring location-provider changes
2021-05-12 18:54:27.608 8094-8129/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
2021-05-12 18:54:27.620 8094-8144/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.data.sqlite.b prune] 
      ℹ️  PRUNE -1 days
2021-05-12 18:54:27.624 8094-8144/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
2021-05-12 18:54:27.650 8094-8144/com.trumsoft.rovermobilegap I/TSLocationManager: [c.t.l.s.ActivityRecognitionService b] 
      🎾  Start motion-activity updates
2021-05-12 18:54:27.661 8094-8134/com.trumsoft.rovermobilegap D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO

```

</details>

**Comment by christocracy** [comment]
No idea what could be your problem.

I suggest you attempt to reproduce your problem in a blank "Hello World" project in isolation of your app code and other plugins.

**Comment by ggiordan** [comment]
I've spent the better part of the day on this. Making sure of versions / correct build / parameters / etc
I've got it, this is the key:
```
Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=XXX.XXXXXXXX.xxxxxxxxxTSLocationManager pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
```
This plugin creates a channel for it's own purposes (the "you're unlicensed popup").

My app creates a bunch of channels as part of it's initialization process.  It then tries to cleanup up after itself so that we don't end up with a big mess in the Notification Settings.  As it turns out, it's cleaning up the TSLocationManager Channel too!

So, the plugin attempts to notify about the lack of a license, the channel is no longer there and boom, the app is dead.

**Comment by christocracy** [comment]
> As it turns out, it's cleaning up the TSLocationManager Channel too!

So don't kill the plugin's notification channel!  It needs that when running its foreground-services while tracking location, not just for the license notification.

**Comment by ggiordan** [comment]
yup.  The cleanup was due to the fact that you can't change a channel after creating it, you can only delete it.  if you want to do something like change the sound, you have to delete the channel and make another with with a different name.
I've updated the code to be a bit more selective in deleting channels and only delete the ones that I explicitly created.  That should do the trick.
