### ISSUE TITLE
Adding geofences causes app crashes on android

### ISSUE THREAD

**Issue by m8xp0w3r** [transistorsoft/cordova-background-geolocation-lt#1335]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android
* OS version: 11 (seen on other Android versions too)
* Device manufacturer / model: Samsung Galaxy Tab A, SM-T510
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`): android 10.1.1
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
this.geolocation.ready({
	locationAuthorizationRequest: 'Always',
	desiredAccuracy: this.geolocation.DESIRED_ACCURACY_HIGH,
	geofenceModeHighAccuracy: true,
	distanceFilter: 0,
	disableElasticity: true,
	backgroundPermissionRationale: {
		title: this.tr('Allow %1 to access to this device\'s location in the background?').arg('{applicationName}'),
		message: this.tr('In order to track the stations in the background, please enable {backgroundPermissionOptionLabel} location permission'),
		positiveAction: this.tr('Change to %1').arg('"{backgroundPermissionOptionLabel}"'),
		negativeAction: this.tr('Cancel')
	},
	//debug
	debug: true,
	logLevel: this.geolocation.LOG_LEVEL_VERBOSE
}).then(() =>
{
	this.geolocation.onGeofence(Ext.bind(this.onGeofence, this));
	this.start();
});
```

## Expected Behavior
All geofence objects were to added successfully like on iOS.

## Actual Behavior
After successfully adding 2000 to 4000 objects, the app crashed on Android because it is out of memory. Our first tests on iOS with this code were successful without any problems.
**Screenshot of the Error**
![image](https://user-images.githubusercontent.com/38067181/157022520-8af80b07-077e-4b24-81f1-5a9326b1b1c6.png)

## Steps to Reproduce

1. Create 7000 new geofence objects. In our application we are using currently 7062 objects
```
const geofences = [];
for (let i = 0; i < 7000; i++)
{
	geofences.push({
	identifier: "index: " +i,
	latitude: 9.99999,
	longitude: 9.99999,
	radius: 200,
	notifyOnEntry: true});
}
```
2. Clear geofences storage
```
window.BackgroundGeolocation.removeGeofences();
```
3. Add created geofences4. 
```
window.BackgroundGeolocation.addGeofences(geofences, () =>(), ()=>());
```

## Context

We are implementing a feature for train drivers to track all passed train stations. On iOS it works fine, but under Android the app crashes when trying to add the needed station data. I have modified the identifier in our code to get the index of the stations inside the log. The last successfully added station has index 2096 (`SSLB` is the original identifier. ` index:2096` is my debug code to identify the index.) . This can be seen in the second line of the provided log data.
`SSLB index:2096`.
The 2096 from this example is no static variable. We have also seen like 4000 successful imports and about 1000 successful imports.
## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
2022-03-07 11:37:29.299 6326-8742/de.diloc.DiLocSyncMobile I/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO create] 
      ✅  SSLB index:2096
2022-03-07 11:37:29.299 6326-8742/de.diloc.DiLocSyncMobile W/libc: pthread_create failed: couldn't allocate 1085440-bytes mapped space: Out of memory
2022-03-07 11:37:29.299 6326-8742/de.diloc.DiLocSyncMobile W/DiLocSyncMobil: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again" (VmSize 4192992 kB)
2022-03-07 11:37:29.300 6326-8742/de.diloc.DiLocSyncMobile W/libc: pthread_create failed: couldn't allocate 1085440-bytes mapped space: Out of memory
2022-03-07 11:37:29.301 6326-8742/de.diloc.DiLocSyncMobile W/DiLocSyncMobil: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again" (VmSize 4193012 kB)
2022-03-07 11:37:29.302 6326-8742/de.diloc.DiLocSyncMobile E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: de.diloc.DiLocSyncMobile, PID: 6326
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:887)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-03-07 11:37:29.307 6326-8742/de.diloc.DiLocSyncMobile E/TSLocationManager: [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
      ‼️  Uncaught Exception: pthread_create (1040KB stack) failed: Try again
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access this device's location even when closed or not in use?","message":"[CHANGEME] This app collects location data for FEATURE X and FEATURE Y.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":""},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":0,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":0,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:887)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-03-07 11:37:29.308 6326-8742/de.diloc.DiLocSyncMobile W/libc: pthread_create failed: couldn't allocate 1085440-bytes mapped space: Out of memory
2022-03-07 11:37:29.308 6326-8742/de.diloc.DiLocSyncMobile W/DiLocSyncMobil: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again" (VmSize 4193124 kB)
2022-03-07 11:37:29.463 6326-8621/de.diloc.DiLocSyncMobile I/DiLocSyncMobil: Background young concurrent copying GC freed 158683(9960KB) AllocSpace objects, 0(0B) LOS objects, 53% free, 8489KB/18MB, paused 1.082ms total 119.275ms

```
</details>

**Comment by christocracy** [comment]
Fixed in version [4.4.2](https://github.com/transistorsoft/cordova-background-geolocation/blob/master/CHANGELOG.md#442--2022-02-16) in private-repo.
