### ISSUE TITLE
App getting Crash after permissions

### ISSUE THREAD

**Issue by toufiqpathan** [transistorsoft/cordova-background-geolocation-lt#1410]
Your Environment
* Plugin version:^4.12.0
* Platform: Android
* OS version: 12 
* Device manufacturer / model: Nexus 6
* Cordova version (`cordova -v`): 11.1.0
* Cordova platform version (`cordova platform ls`): 11.0.0
* Plugin config provided to `#ready`:
```javascript <!-- syntax-highlighting:  paste your code below -->
  var bgGeo = window.BackgroundGeolocation;
         
            // 2. Execute #ready method:
            bgGeo.ready({
                reset: true,
                debug: false,
                logLevel: bgGeo.LOG_LEVEL_OFF,
                desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                distanceFilter: 10,
                allowIdenticalLocations: true,
                autoSync: true,
                stopOnTerminate: false,
                //startOnBoot: true
            }, function(state) {
                var deferred = $.Deferred();   // <-- Current state provided to #configure callback
                
                deferred.done(function () {
                       var stopdeferred = $.Deferred();
                        stopdeferred.done(function () {
                            var backgroundInterval = 5000;
                            if(localStorage.getItem("isBackgroundMode") == "true"){
                                backgroundInterval = 45000;
                            }
                            bgGeo.watchPosition((location) => {
                          //  console.log("LOCATION:::::", JSON.parse(JSON.stringify(location)))
                            self.geoLocationSuccess(JSON.parse(JSON.stringify(location)));
                            },(error) => {
                          //   console.log("LOCATION error:::::", JSON.parse(JSON.stringify(error)))
                            },{interval:backgroundInterval,  persist: false});
                        });
                        bgGeo.stopWatchPosition().then(function (){
                            stopdeferred.resolve();
                        }).catch(err => {
                            stopdeferred.resolve();
                        });
        
                       
                });
                // 3.  Start tracking
                console.log('BackgroundGeolocation is configured and ready to use',JSON.parse(JSON.stringify(state)));
                // if (window.cordova.platformId == 'android') {
                //     console.log("IN ANDROID::::");
               state.enabled = false;
               // }
               console.log("ENABLE STATUS:::::",state.enabled)
                if (!state.enabled) {
                    bgGeo.start().then(function() {
                    console.log('- BackgroundGeolocation tracking started');
                    Logs.logWrite('[INFO] - BackgroundGeolocation tracking started');
                   // self.geoLocationSuccess(isLocationDetails);
                  
                   deferred.resolve();
                  
                }).catch(err => {
                    console.log("IN ERROR OF START BGO::::", err);
                    deferred.resolve();
                });
                } 
               
                
            });
           
```

## Expected Behavior
App should launch

## Actual Behavior
While giving the permission app getting close / crash.

## Steps to Reproduce

1.
2.
3.
4.

## Context
open the app

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE 
 runtime.cc:669]   native: #02 pc 00000000000c688a  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_timedwait+90)
                                                                                                    runtime.cc:669]   native: #03 pc 00000000011c16f9  /data/app/~~d9-gO9gpXepJaLrAPbH-jQ==/com.google.android.trichromelibrary_447211487-DU9PQ8rsVdFbvrYBaoZfTw==/TrichromeLibrary.apk!libmonochrome_64.so (offset 647000) (???)
                                                                                                    runtime.cc:669]   (no managed stack frames)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "MemoryInfra" prio=5 tid=78 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x136401c8 self=0x71400e9d3430
                                                                                                    runtime.cc:669]   | sysTid=5013 nice=0 cgrp=top-app sched=0/0 handle=0x713e1bca2cf0
                                                                                                    runtime.cc:669]   | state=S schedstat=( 24254310 47620452 20 ) utm=0 stm=2 core=4 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x713e1bbac000-0x713e1bbae000 stackSize=987KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 000000000005ad18  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+24)
                                                                                                    runtime.cc:669]   native: #01 pc 000000000005f342  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+146)
                                                                                                    runtime.cc:669]   native: #02 pc 00000000000c688a  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_timedwait+90)
                                                                                                    runtime.cc:669]   native: #03 pc 00000000011c16f9  /data/app/~~d9-gO9gpXepJaLrAPbH-jQ==/com.google.android.trichromelibrary_447211487-DU9PQ8rsVdFbvrYBaoZfTw==/TrichromeLibrary.apk!libmonochrome_64.so (offset 647000) (???)
                                                                                                    runtime.cc:669]   (no managed stack frames)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "JavaBridge" prio=5 tid=55 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x136403d0 self=0x71400e9e81f0
                                                                                                    runtime.cc:669]   | sysTid=5493 nice=0 cgrp=top-app sched=0/0 handle=0x713e1a964cf0
                                                                                                    runtime.cc:669]   | state=S schedstat=( 138936029 220541195 131 ) utm=1 stm=12 core=3 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x713e1a862000-0x713e1a864000 stackSize=1035KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 00000000000b38ca  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+10)
                                                                                                    runtime.cc:669]   native: #01 pc 000000000001817a  /system/lib64/libutils.so (android::Looper::pollInner(int)+250)
                                                                                                    runtime.cc:669]   native: #02 pc 000000000001801e  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+126)
                                                                                                    runtime.cc:669]   native: #03 pc 0000000000169bc3  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+35)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.nativePollOnce(Native method)
                                                                                                    runtime.cc:669]   at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    runtime.cc:669]   at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    runtime.cc:669]   at android.os.Looper.loop(Looper.java:288)
                                                                                                    runtime.cc:669]   at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] "pool-29-thread-3" prio=5 tid=84 Native
                                                                                                    runtime.cc:669]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x13640328 self=0x71400e9eb990
                                                                                                    runtime.cc:669]   | sysTid=5532 nice=0 cgrp=top-app sched=0/0 handle=0x713e10e2acf0
                                                                                                    runtime.cc:669]   | state=S schedstat=( 173815804 112464344 150 ) utm=1 stm=16 core=1 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x713e10d28000-0x713e10d2a000 stackSize=1035KB
                                                                                                    runtime.cc:669]   | held mutexes=
                                                                                                    runtime.cc:669]   native: #00 pc 000000000005ad16  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+22)
2023-07-13 08:44:34.076  4830-5505  de247.ctpdrive          latitude247.ctpdriver                A  runtime.cc:669]   native: #01 pc 0000000000425d1e  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+110)
                                                                                                    runtime.cc:669]   native: #02 pc 0000000000675c0c  /apex/com.android.art/lib64/libart.so (art::JNI<false>::NewObjectArray(_JNIEnv*, int, _jclass*, _jobject*)+540)
                                                                                                    runtime.cc:669]   native: #03 pc 0000000000173d58  /system/lib64/libandroid_runtime.so (android::NativeList(_JNIEnv*, _jclass*, long, _jstring*)+424)
                                                                                                    runtime.cc:669]   at android.content.res.AssetManager.nativeList(Native method)
                                                                                                    runtime.cc:669]   at android.content.res.AssetManager.list(AssetManager.java:929)
                                                                                                    runtime.cc:669]   - locked <0x0959a739> (a android.content.res.AssetManager)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.AssetFilesystem.listAssets(SourceFile:8)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.AssetFilesystem.isDirectory(SourceFile:-1)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.AssetFilesystem.toLocalUri(SourceFile:16)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.Filesystem.makeEntryForNativeUri(SourceFile:1)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.Filesystem.getRootEntry(SourceFile:2)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.FileUtils.requestAllFileSystems(SourceFile:3)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.FileUtils.access$400(SourceFile:-1)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.FileUtils$11.run(SourceFile:-1)
                                                                                                    runtime.cc:669]   at org.apache.cordova.file.FileUtils$25.run(SourceFile:2)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    runtime.cc:669]   at java.lang.Thread.run(Thread.java:920)
                                                                                                    runtime.cc:669] 
                                                                                                    runtime.cc:669] Aborting thread:
                                                                                                    runtime.cc:669] "pool-29-thread-2" prio=5 tid=83 Native
                                                                                                    runtime.cc:669]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x13640240 self=0x71400e9ed560
                                                                                                    runtime.cc:669]   | sysTid=5505 nice=0 cgrp=top-app sched=0/0 handle=0x713e14b0fcf0
                                                                                                    runtime.cc:669]   | state=R schedstat=( 446774319 449811516 418 ) utm=6 stm=37 core=5 HZ=100
                                                                                                    runtime.cc:669]   | stack=0x713e14a0d000-0x713e14a0f000 stackSize=1035KB
                                                                                                    runtime.cc:669]   | held mutexes= "abort lock"
                                                                                                    runtime.cc:669]   native: #00 pc 000000000073ccef  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+127)
                                                                                                    runtime.cc:669]   native: #01 pc 00000000008824e0  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+368)
                                                                                                    runtime.cc:669]   native: #02 pc 000000000083a229  /apex/com.android.art/lib64/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+57)
                                                                                                    runtime.cc:669]   native: #03 pc 0000000000822772  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2546)
                                                                                                    runtime.cc:669]   native: #04 pc 00000000000194ac  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+60)
                                                                                                    runtime.cc:669]   native: #05 pc 0000000000018ac0  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352)
                                                                                                    runtime.cc:669]   native: #06 pc 000000000061c505  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2741)
                                                                                                    runtime.cc:669]   native: #07 pc 0000000000633830  /apex/com.android.art/lib64/libart.so (art::JNI<false>::NewObject(_JNIEnv*, _jclass*, _jmethodID*, ...)+240)
                                                                                                    runtime.cc:669]   native: #08 pc 00000000003a03ab  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+219)
                                                                                                    runtime.cc:669]   native: #09 pc 000000000038baed  /apex/com.android.art/lib64/libart.so (nterp_helper+165)
2023-07-13 08:44:34.077  4830-5505  de247.ctpdrive          latitude247.ctpdriver                A  runtime.cc:669]   native: #10 pc 0000000000b7dd3a  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.b.c+30)
                                                                                                    runtime.cc:669]   native: #11 pc 000000000038d63d  /apex/com.android.art/lib64/libart.so (nterp_helper+7157)
                                                                                                    runtime.cc:669]   native: #12 pc 0000000000b7e5ba  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.f.<init>+26)
                                                                                                    runtime.cc:669]   native: #13 pc 000000000038c8e0  /apex/com.android.art/lib64/libart.so (nterp_helper+3736)
                                                                                                    runtime.cc:669]   native: #14 pc 0000000000b7de00  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.e.a+4)
                                                                                                    runtime.cc:669]   native: #15 pc 000000000038c8e0  /apex/com.android.art/lib64/libart.so (nterp_helper+3736)
                                                                                                    runtime.cc:669]   native: #16 pc 0000000000ba5446  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.b.i+14)
                                                                                                    runtime.cc:669]   native: #17 pc 000000000038c8e0  /apex/com.android.art/lib64/libart.so (nterp_helper+3736)
                                                                                                    runtime.cc:669]   native: #18 pc 0000000000ba5cec  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin.j+124)
                                                                                                    runtime.cc:669]   native: #19 pc 000000000038c8e0  /apex/com.android.art/lib64/libart.so (nterp_helper+3736)
                                                                                                    runtime.cc:669]   native: #20 pc 0000000000ba5c54  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin.a)
                                                                                                    runtime.cc:669]   native: #21 pc 000000000038ba80  /apex/com.android.art/lib64/libart.so (nterp_helper+56)
                                                                                                    runtime.cc:669]   native: #22 pc 0000000000ba57b4  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin$d.run+24)
                                                                                                    runtime.cc:669]   native: #23 pc 00000000003e1f6d  /apex/com.android.art/javalib/x86_64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+1101)
                                                                                                    runtime.cc:669]   native: #24 pc 00000000003da6b2  /apex/com.android.art/javalib/x86_64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+66)
                                                                                                    runtime.cc:669]   native: #25 pc 00000000001e3fa2  /apex/com.android.art/javalib/x86_64/boot.oat (java.lang.Thread.run+82)
                                                                                                    runtime.cc:669]   native: #26 pc 0000000000395094  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+756)
                                                                                                    runtime.cc:669]   native: #27 pc 000000000041da7a  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+218)
                                                                                                    runtime.cc:669]   native: #28 pc 000000000081aa6e  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+478)
                                                                                                    runtime.cc:669]   native: #29 pc 000000000087a03f  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1343)
                                                                                                    runtime.cc:669]   native: #30 pc 00000000000c74aa  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+58)
                                                                                                    runtime.cc:669]   native: #31 pc 000000000005fca7  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55)
                                                                                                    runtime.cc:669]   at io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(Native method)
                                                                                                    runtime.cc:669]   at i6.b.c(SourceFile:2)
                                                                                                    runtime.cc:669]   at i6.f.<init>(SourceFile:4)
                                                                                                    runtime.cc:669]   at i6.e.a(SourceFile:-1)
                                                                                                    runtime.cc:669]   at io.sqlc.b.i(SourceFile:-1)
                                                                                                    runtime.cc:669]   at io.sqlc.SQLitePlugin.j(SourceFile:6)
                                                                                                    runtime.cc:669]   at io.sqlc.SQLitePlugin.a(SourceFile:-1)
                                                                                                    runtime.cc:669]   at io.sqlc.SQLitePlugin$d.run(SourceFile:1)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    runtime.cc:669]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    runtime.cc:669]   at java.lang.Thread.run(Thread.java:920)
2023-07-13 08:44:34.077  4830-5505  de247.ctpdrive          latitude247.ctpdriver                A  runtime.cc:669] Pending exception java.lang.NoSuchMethodError: no non-static method "Lio/liteglue/SQLiteNativeResponse;.<init>(IJ)V"
                                                                                                    runtime.cc:669]   at io.liteglue.SQLiteNativeResponse io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(java.lang.String, int) (SourceFile:-2)
                                                                                                    runtime.cc:669]   at int i6.b.c() (SourceFile:2)
                                                                                                    runtime.cc:669]   at void i6.f.<init>(java.lang.String, int) (SourceFile:4)
                                                                                                    runtime.cc:669]   at i6.d i6.e.a(java.lang.String, int) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at void io.sqlc.b.i(java.io.File) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at io.sqlc.a io.sqlc.SQLitePlugin.j(java.lang.String, org.apache.cordova.CallbackContext, boolean) (SourceFile:6)
                                                                                                    runtime.cc:669]   at io.sqlc.a io.sqlc.SQLitePlugin.a(io.sqlc.SQLitePlugin, java.lang.String, org.apache.cordova.CallbackContext, boolean) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at void io.sqlc.SQLitePlugin$d.run() (SourceFile:1)
                                                                                                    runtime.cc:669]   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
                                                                                                    runtime.cc:669]   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
                                                                                                    runtime.cc:669]   at void java.lang.Thread.run() (Thread.java:920)
                                                                                                    runtime.cc:669] 
2023-07-13 08:44:34.082  4830-4830  FIAM.Display            latitude247.ctpdriver                I  Binding to activity: com.transistorsoft.locationmanager.activity.TSLocationManagerActivity
2023-07-13 08:44:34.083  4830-4830  FIAM.Headless           latitude247.ctpdriver                I  Setting display event component
2023-07-13 08:44:34.084  4830-5505  de247.ctpdrive          latitude247.ctpdriver                A  runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: mid == null
                                                                                                    runtime.cc:677]     in call to NewObject
                                                                                                    runtime.cc:677]     from io.liteglue.SQLiteNativeResponse io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(java.lang.String, int)
2023-07-13 08:44:34.148  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(371)] "on pause...", source: file:///android_asset/www/scripts/indexmain.js (371)
2023-07-13 08:44:34.156  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(561)] "BackgroundGeolocation is configured and ready to use [object Object]", source: file:///android_asset/www/scripts/gps/locationprovider.js (561)
2023-07-13 08:44:34.158  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(566)] "ENABLE STATUS::::: false", source: file:///android_asset/www/scripts/gps/locationprovider.js (566)
2023-07-13 08:44:34.176  4830-4830  Choreographer           latitude247.ctpdriver                I  Skipped 33 frames!  The application may be doing too much work on its main thread.
2023-07-13 08:44:34.884  4830-4845  OpenGLRenderer          latitude247.ctpdriver                I  Davey! duration=1233ms; Flags=1, FrameTimelineVsyncId=4400, IntendedVsync=154105950888, Vsync=154655950866, InputEventId=0, HandleInputStart=154670134500, AnimationStart=154670182500, PerformTraversalsStart=154670456900, DrawStart=155133840400, FrameDeadline=154122617554, FrameInterval=154669444000, FrameStartTime=16666666, SyncQueued=155134175200, SyncStart=155138734700, IssueDrawCommandsStart=155139157500, SwapBuffers=155334378200, FrameCompleted=155343556100, DequeueBufferDuration=179800, QueueBufferDuration=7374100, GpuCompleted=155342825400, SwapBuffersCompleted=155343556100, DisplayPresentTime=64, 
2023-07-13 08:44:35.175  4830-4830  Choreographer           latitude247.ctpdriver                I  Skipped 55 frames!  The application may be doing too much work on its main thread.
2023-07-13 08:44:35.222  4830-4830  FIAM.Display            latitude247.ctpdriver                I  Unbinding from activity: com.transistorsoft.locationmanager.activity.TSLocationManagerActivity
2023-07-13 08:44:35.224  4830-4830  FIAM.Headless           latitude247.ctpdriver                I  Removing display event component
2023-07-13 08:44:35.562  4830-4830  FIAM.Display            latitude247.ctpdriver                I  Binding to activity: com.intentfilter.androidpermissions.PermissionsActivity
2023-07-13 08:44:35.563  4830-4830  FIAM.Headless           latitude247.ctpdriver                I  Setting display event component
2023-07-13 08:44:35.643  4830-4830  FIAM.Display            latitude247.ctpdriver                I  Unbinding from activity: com.intentfilter.androidpermissions.PermissionsActivity
2023-07-13 08:44:35.644  4830-4830  FIAM.Headless           latitude247.ctpdriver                I  Removing display event component
2023-07-13 08:44:36.164  4830-4933  EGL_emulation           latitude247.ctpdriver                D  app_time_stats: avg=4687.11ms min=4687.11ms max=4687.11ms count=1
2023-07-13 08:44:36.791  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(46)] "got main dir [object Object]", source: file:///android_asset/www/scripts/common/logs.js (46)
2023-07-13 08:44:37.052  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(49)] "got the file [object Object]", source: file:///android_asset/www/scripts/common/logs.js (49)
2023-07-13 08:44:37.717  4830-4933  EGL_emulation           latitude247.ctpdriver                D  app_time_stats: avg=768.12ms min=572.52ms max=963.72ms count=2
2023-07-13 08:44:38.459  4830-4839  de247.ctpdrive          latitude247.ctpdriver                I  Background young concurrent copying GC freed 33465(2093KB) AllocSpace objects, 22(824KB) LOS objects, 29% free, 6749KB/9620KB, paused 8.158ms,446us total 44.119ms
--------- beginning of crash
2023-07-13 08:44:40.807  4830-5505  libc                    latitude247.ctpdriver                A  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5505 (pool-29-thread-), pid 4830 (de247.ctpdriver)
2023-07-13 08:44:41.703  4830-4830  chromium                latitude247.ctpdriver                I  [INFO:CONSOLE(194)] "case 1", source: file:///android_asset/www/scripts/common/logs.js (194)
2023-07-13 08:44:43.532  5748-5748  DEBUG                   pid-5748                             A  Cmdline: latitude247.ctpdriver
2023-07-13 08:44:43.534  5748-5748  DEBUG                   pid-5748                             A  pid: 4830, tid: 5505, name: pool-29-thread-  >>> latitude247.ctpdriver <<<
2023-07-13 08:44:43.588  5748-5748  DEBUG                   pid-5748                             A        #08 pc 0000000000b7dd3a  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.b.c+30)
2023-07-13 08:44:43.589  5748-5748  DEBUG                   pid-5748                             A        #10 pc 0000000000b7e5ba  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.f.<init>+26)
2023-07-13 08:44:43.593  5748-5748  DEBUG                   pid-5748                             A        #12 pc 0000000000b7de00  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (i6.e.a+4)
2023-07-13 08:44:43.598  5748-5748  DEBUG                   pid-5748                             A        #14 pc 0000000000ba5446  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.b.i+14)
2023-07-13 08:44:43.600  5748-5748  DEBUG                   pid-5748                             A        #16 pc 0000000000ba5cec  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin.j+124)
2023-07-13 08:44:43.625  5748-5748  DEBUG                   pid-5748                             A        #18 pc 0000000000ba5c54  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin.a+0)
2023-07-13 08:44:43.626  5748-5748  DEBUG                   pid-5748                             A        #20 pc 0000000000ba57b4  /data/app/~~x0GwFmVZQfHGv3IDqQTKQg==/latitude247.ctpdriver-lImYNC-ZHOZRGLnPWHwC6Q==/oat/x86_64/base.vdex (io.sqlc.SQLitePlugin$d.run+24)
2023-07-13 08:44:44.435  4830-4830  Compatibil...geReporter latitude247.ctpdriver                D  Compat change id reported: 160794467; UID 10156; state: ENABLED
2023-07-13 08:44:44.791  4830-4830  WindowManager           latitude247.ctpdriver                E  android.view.WindowLeaked: Activity com.transistorsoft.locationmanager.activity.TSLocationManagerActivity has leaked window DecorView@b825309[TSLocationManagerActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:812)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:796)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:390)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:138)
                                                                                                    	at android.app.Dialog.show(Dialog.java:348)
                                                                                                    	at com.transistorsoft.locationmanager.config.TSBackgroundPermissionRationale.onStartActivity(Unknown Source:131)
                                                                                                    	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.requestBackgroundLocationPermission(Unknown Source:24)
                                                                                                    	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.execute(Unknown Source:63)
                                                                                                    	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:14)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8054)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8034)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)-->
```

</details>

**Comment by christocracy** [comment]
I would have a look at what you're doing with this *SQLitePlugin*.

```
Pending exception java.lang.NoSuchMethodError: no non-static method "Lio/liteglue/SQLiteNativeResponse;.<init>(IJ)V"
                                                                                                    runtime.cc:669]   at io.liteglue.SQLiteNativeResponse io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(java.lang.String, int) (SourceFile:-2)
                                                                                                    runtime.cc:669]   at int i6.b.c() (SourceFile:2)
                                                                                                    runtime.cc:669]   at void i6.f.<init>(java.lang.String, int) (SourceFile:4)
                                                                                                    runtime.cc:669]   at i6.d i6.e.a(java.lang.String, int) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at void io.sqlc.b.i(java.io.File) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at io.sqlc.a io.sqlc.SQLitePlugin.j(java.lang.String, org.apache.cordova.CallbackContext, boolean) (SourceFile:6)
                                                                                                    runtime.cc:669]   at io.sqlc.a io.sqlc.SQLitePlugin.a(io.sqlc.SQLitePlugin, java.lang.String, org.apache.cordova.CallbackContext, boolean) (SourceFile:-1)
                                                                                                    runtime.cc:669]   at void io.sqlc.SQLitePlugin$d.run() (SourceFile:1)
                                                                                                    runtime.cc:669]   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
                                                                                                    runtime.cc:669]   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
                                                                                                    runtime.cc:669]   at void java.lang.Thread.run() (Thread.java:920)
```
