### ISSUE TITLE
[IOS] Cannot archive application due to build errors in xcode

### ISSUE THREAD

**Issue by dackyD** [transistorsoft/cordova-background-geolocation-lt#1416]
## Your Environment
* Plugin version: 4.14.2
* Platform: iOS
* IOS version: 16.13.1
* MAC OS version: Ventura 13.5.1
* XCODE version: 14.3.1
* Device manufacturer / model: iPhone X
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`):  7.0.0

## Expected Behavior
Should archive ios build without errors when running cordova build ios or building in xcode

## Actual Behavior
Cannot archive ios build when running cordova build ios or buidling in xcode.
The project builds and archives without errors in the command line by running cordova build ios or building in xcode when cordova-background-geolocation-lt is removed.

## Debug logs

<details>
	<summary>Logs</summary>

```<!-- Syntax highlighting:  DO NOT REMOVE -->
======> Logs when building from xcode:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_DDASLLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_CLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in TSLocationManager(TSGeofenceManager.o)
      objc-class-ref in TSLocationManager(TSGeofenceEvent.o)
      objc-class-ref in TSLocationManager(TSScheduler.o)
      objc-class-ref in TSLocationManager(TSLocation.o)
      objc-class-ref in TSLocationManager(SOMotionDetector.o)
      objc-class-ref in TSLocationManager(TSLog.o)
      objc-class-ref in TSLocationManager(TSSchedule.o)
      ...
  "_OBJC_CLASS_$_DDOSLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
      objc-class-ref in TSLocationManager(TSLog.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._maxAge", referenced from:
      -[TSDBLogger getLog:] in TSLocationManager(TSDBLogger.o)
      -[TSDBLogger db_delete] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractDatabaseLogger._saveThreshold", referenced from:
      -[TSDBLogger initWithLogDirectory:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDAbstractLogger._logFormatter", referenced from:
      -[TSDBLogger db_log:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._context", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._flag", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._message", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_IVAR_$_DDLogMessage._timestamp", referenced from:
      -[TSDBLogEntry initWithLogMessage:] in TSLocationManager(TSDBLogger.o)
  "_OBJC_METACLASS_$_DDAbstractDatabaseLogger", referenced from:
      _OBJC_METACLASS_$_TSDBLogger in TSLocationManager(TSDBLogger.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

======> Logs from command line when running cordova build ios:

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 43498f2cc4f4129a300eafc0eaf07888
Build description path: /Users/hdd/Library/Developer/Xcode/DerivedData/Effera_Insight-hbzvppfxfzglvrdxxdkszwpohxyk/Build/Intermediates.noindex/ArchiveIntermediates/Effera Insight/IntermediateBuildFilesPath/XCBuildData/43498f2cc4f4129a300eafc0eaf07888.xcbuilddata

note: Building targets in dependency order
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'FirebaseCore' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'FirebaseCoreInternal' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'GoogleUtilities' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'PromisesObjC' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'nanopb' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'FirebaseInstallations' from project 'Pods')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Effera Insight.xcodeproj: error: Signing for "Effera Insight" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Effera Insight' from project 'Effera Insight')
/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'GoogleDataTransport' from project 'Pods')
** ARCHIVE FAILED **

Command failed with exit code 65: xcodebuild -workspace Effera Insight.xcworkspace -scheme Effera Insight -configuration Debug -destination generic/platform=iOS -archivePath Effera Insight.xcarchive archive
Error: Command failed with exit code 65: xcodebuild -workspace Effera Insight.xcworkspace -scheme Effera Insight -configuration Debug -destination generic/platform=iOS -archivePath Effera Insight.xcarchive archive
    at makeError (/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/hdd/Dev/Effera/EfferaNx.Beta/src/Clients/Effera.Platform.ClientApp/apps/client-app/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] An error occurred while running subprocess cordova.

```

</details>

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by christocracy** [comment]
(use **triple backticks to syntax highlight multiline code-blocks**.  Not *one*.)

Show me also the following file:  `platforms/ios/Podfile`

**Comment by dackyD** [comment]
PodFIle

```
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'
use_frameworks!
target 'Insight' do
	project 'Insight.xcodeproj'
	pod 'Firebase/Messaging', '~> 8.1.1'
	pod 'CocoaLumberjack', '~> 3.7.2'
end

```

**Comment by christocracy** [comment]
- Why are you using this [cordova-android-support-gradle-release](https://github.com/dpa99c/cordova-android-support-gradle-release) which is marked **DEPRECATED** and **READ-ONLY** and hasn't [seen a release in 4 years](https://www.npmjs.com/package/cordova-android-support-gradle-release)?:

- Also [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) is no longer necessary.  See [here](https://stackoverflow.com/questions/59429175/migrating-a-cordova-android-project-to-androidx)

- [cordova-plugin-cocoapods-support](https://github.com/dpa99c/cordova-plugin-cocoapods-support):  **DEPRECATED**.
- [cordova-plugin-hce](https://www.npmjs.com/package/cordova-plugin-hce):  **NO UPDATE IN 8 YEARS**
- [es6-promise-plugin](https://www.npmjs.com/package/es6-promise-plugin):  **NO UPDATE IN 6 YEARS**.
- [wifiwizard](https://www.npmjs.com/package/wifiwizard2):  **NO UPDATE IN 4 YEARS**.

I suggest you first `cordova platform remove ios` / `cordova plugin add ios` and try again.

Then **AUDIT YOUR PLUGINS**.

**Comment by dackyD** [comment]
Hi Chris,

I can't really answer why I am using those plugins because I inherited this project.
You are entirely correct, as I started to remove those plugins you mentioned, the compile error from xcode went away.

I really appreciate the support. I am closing this ticket since this is not related to cordova-background-geolocation-lt.

Thanks again for the support.
