### ISSUE TITLE
Geolocation runtime app crash reported from Google Play

### ISSUE THREAD

**Issue by QA-NathanOlsen** [transistorsoft/cordova-background-geolocation-lt#365]
application version
100125
Android version
Android 7.0
Device
Galaxy S7 Edge (hero2qltetmo)
Manufacturer Samsung RAM (MB) 4096 Screen size 1440 × 2560 Screen density (dpi) 640 Native platform armeabi-v7a OpenGL ES version 3.1 CPU make Qualcomm CPU model MSM8996

java.lang.NullPointerException: 
  at com.transistorsoft.locationmanager.LocationService.onHandleIntent(Unknown Source:0)
  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by christocracy** [comment]
Can you get plugin logs from this device?

Can you reproduce this?

**Comment by QA-NathanOlsen** [comment]
@christocracy I haven't been able to replicate it here in our QA tests. We first saw the error after release to production and unfortunately I don't have access to that device. I will be tracking this issue for more reports from google play.

**Comment by christocracy** [comment]
Closed for lack of feedback.
