### ISSUE TITLE
Configure function never returns on android

### ISSUE THREAD

**Issue by dtruel** [transistorsoft/cordova-background-geolocation-lt#579]
The following code never calls the success or failure callbacks on android. It seems to work fine on iOS.  I do not get any license validation issue.

```javascript
BackgroundGeolocation.configure({
    desiredAccuracy: 100,
    distanceFilter: 400,
    activityRecognitionInterval: 30,
    url: defaultPostLocation,
    stopOnTerminate: false,
    startOnBoot: true,
    batchSync: false,
    autoSync: true,
    method: "POST",
}, function (state) {
    BackgroundGeolocation.start();
    console.log("starging bglocation")
}, function (err) {
    console.error("error configuring bglocation")
    console.error(err);
    reject(err);
    alert("Error configuring background geolocation")
});
```
## Your Environment
* Plugin version: cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung Galaxy J1 mini prime (SM-J106B)
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin config

## Debug logs
```
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:995)
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:100)
12-30 00:18:02.888 19988-20194/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
```

**Comment by christocracy** [comment]
You're not showing the full stacktrace.

**Comment by dtruel** [comment]
Here we go:
```
01-02 12:22:20.656 22336-22500/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
01-02 12:22:20.666 22336-22500/? W/System.err: java.lang.IncompatibleClassChangeError: com.google.android.gms.location.ActivityRecognitionResult
01-02 12:22:20.666 22336-22500/? W/System.err:     at dalvik.system.DexFile.defineClassNative(Native Method)
01-02 12:22:20.666 22336-22500/? W/System.err:     at dalvik.system.DexFile.defineClass(DexFile.java:226)
01-02 12:22:20.666 22336-22500/? W/System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
01-02 12:22:20.666 22336-22500/? W/System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:338)
01-02 12:22:20.666 22336-22500/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
01-02 12:22:20.666 22336-22500/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-02 12:22:20.666 22336-22500/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
01-02 12:22:20.666 22336-22500/? W/System.err:     at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
01-02 12:22:20.666 22336-22500/? W/System.err:     at java.lang.Class.getDexCacheType(Class.java:476)
01-02 12:22:20.666 22336-22500/? W/System.err:     at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
01-02 12:22:20.666 22336-22500/? W/System.err:     at java.lang.reflect.Method.getParameterTypes(Method.java:170)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:995)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:100)
01-02 12:22:20.666 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-02 12:22:20.666 22336-22500/? W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
01-02 12:22:20.666 22336-22500/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 12:22:20.666 22336-22500/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-02 12:22:20.666 22336-22500/? W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
01-02 12:22:20.676 22336-22500/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
01-02 12:22:20.676 22336-22500/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
01-02 12:22:20.676 22336-22500/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
01-02 12:22:20.676 22336-22500/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
01-02 12:22:20.676 22336-22500/? W/System.err: java.lang.IncompatibleClassChangeError: com.google.android.gms.location.ActivityRecognitionResult
01-02 12:22:20.676 22336-22500/? W/System.err:     at dalvik.system.DexFile.defineClassNative(Native Method)
01-02 12:22:20.676 22336-22500/? W/System.err:     at dalvik.system.DexFile.defineClass(DexFile.java:226)
01-02 12:22:20.676 22336-22500/? W/System.err:     at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
01-02 12:22:20.676 22336-22500/? W/System.err:     at dalvik.system.DexPathList.findClass(DexPathList.java:338)
01-02 12:22:20.676 22336-22500/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
01-02 12:22:20.676 22336-22500/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
01-02 12:22:20.676 22336-22500/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
01-02 12:22:20.676 22336-22500/? W/System.err:     at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
01-02 12:22:20.676 22336-22500/? W/System.err:     at java.lang.Class.getDexCacheType(Class.java:476)
01-02 12:22:20.676 22336-22500/? W/System.err:     at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
01-02 12:22:20.676 22336-22500/? W/System.err:     at java.lang.reflect.Method.getParameterTypes(Method.java:170)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:995)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:100)
01-02 12:22:20.676 22336-22500/? W/System.err:     at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-02 12:22:20.676 22336-22500/? W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
01-02 12:22:20.676 22336-22500/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 12:22:20.676 22336-22500/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-02 12:22:20.676 22336-22500/? W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by christocracy** [comment]
I switched to using updated play-services APIs which now require minimum play-services version of `11.2.0`

Paste your `platforms/android/project.properties`.  You'll find some other plugins are likely importing version `+` or versions less than `11.2.0`

**Comment by dtruel** [comment]
This is what it has by default.
```
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.firebase:firebase-core:11.6.0
cordova.system.library.2=com.android.volley:volley:1.0.0
cordova.gradle.include.1=cordova-plugin-firebase-weathercall/push-build.gradle
cordova.system.library.3=me.leolin:ShortcutBadger:1.1.18@aar
cordova.system.library.4=com.google.firebase:firebase-messaging:+
cordova.system.library.5=com.google.firebase:firebase-crash:+
cordova.system.library.6=com.google.firebase:firebase-config:+
cordova.system.library.7=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.8=com.android.support:appcompat-v7:26.1.0
cordova.system.library.9=com.google.android.gms:play-services-location:$GOOGLE_API_VERSION
cordova.system.library.10=com.android.support:appcompat-v7:$APPCOMPAT_VERSION
cordova.gradle.include.2=cordova-background-geolocation-lt/push-build.gradle
```
Unfortunately it won't build, saying: Could not get unknown property 'GOOGLE_API_VERSION'. It also says the same error about $APPCOMPAT_VERSION.  So I went to the buiild.grade and got rid of these two lines because they are redundant
```
cordova.system.library.9=com.google.android.gms:play-services-location:$GOOGLE_API_VERSION
cordova.system.library.10=com.android.support:appcompat-v7:$APPCOMPAT_VERSION
```

Still had the same error though.

**Comment by christocracy** [comment]
these variables are supposed to be evaluated.  You're not using platform `cordova-android >= 6.3.0`.  

```
cordova.system.library.9=com.google.android.gms:play-services-location:$GOOGLE_API_VERSION
```

It should look like this:
```
cordova.system.library.1=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
```

Remove your android platform and re-add it.  Ensure you've got `cordova-android >= 6.3.0`

Also, these are going to cause issues:

```
cordova.system.library.4=com.google.firebase:firebase-messaging:+
cordova.system.library.5=com.google.firebase:firebase-crash:+
cordova.system.library.6=com.google.firebase:firebase-config:+
```

**Comment by kasperbauer** [comment]
I'm having the same problem, here's my project.properties file:

```
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-base:+
cordova.system.library.2=com.google.android.gms:play-services-ads:+
cordova.gradle.include.1=cordova-fabric-plugin/guardian-build-extras.gradle
cordova.gradle.include.2=cordova-plugin-firebase/guardian-build.gradle
cordova.system.library.3=com.google.gms:google-services:+
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-crash:+
cordova.system.library.8=com.google.firebase:firebase-config:+
cordova.system.library.9=com.google.android.gms:play-services-location:11.6.0
cordova.system.library.10=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation/guardian-build.gradle
```

I guess theres a conflict with cordova-plugin-firebase, so thats up to the firebase team?

**Comment by christocracy** [comment]
Correct.  I’m working on a fork where I completely refactor their dependency-mgmt.  pay close attention to the README to solve issues, particularly for iOS if you’ve never dealt with cocoapods before.

https://github.com/transistorsoft/cordova-plugin-firebase

**Comment by dtruel** [comment]
@christocracy Thanks for the help, and also for your contributions to the firebase plugin... The cordova community needs as much help as it can get.

I upgraded cordova-android to 6.4.0 and that fixed one error.  But I still couldn't get location to work. So I just reinstalled cordova-background-geolocation@2.7.6 and it works, so I'll just stick with that for now.

**Comment by christocracy** [comment]
You’re going to have issues with iOS 11 / Android 8 if you simply give up and use an old version.  Don’t be lazy.

**Comment by dtruel** [comment]
Hm, what are the issues and how serious are they?

**Comment by christocracy** [comment]
Are you not testing for yourself on latest iOS / Android.

**Comment by kasperbauer** [comment]
@christocracy Do you have any timetable when to expect a working fork? Thanks a lot. :)

**Comment by christocracy** [comment]
@kasperbauer working fork of `cordova-plugin-firebase`?

**Comment by kasperbauer** [comment]
@christocracy yep.

**Comment by christocracy** [comment]
Have you tried it?  If you have a problem, post an issue there.

**Comment by dtruel** [comment]
Well I realized that the reason I upgraded was because the downgraded version doesn't work on iOS 11.  So I've got to figure this out.

**Comment by kasperbauer** [comment]
@christocracy I missed the cordova-7.1.0 branch. Thanks. :)

**Comment by christocracy** [comment]
@markacianfrani you’re going to have a nice fine time trying to align 4 plugins to same play-Services version.

Both my plugin and phonegap-plugin push expose config variables to assist with that (`GOOGLE_API_VERSION` and `FCM_VERSION`) respectively.

The other 2 probably have their version hard-coded in their plugin.xml, so your only option would be to fork those plugin or beg the authors to implement a config variable to control the version.

Or you manually edit `platforms/android/project.properies`.
