### ISSUE TITLE
Android 8.1 - Crash only when running signed APK

### ISSUE THREAD

**Issue by jwburnside** [transistorsoft/cordova-background-geolocation-lt#679]
## Your Environment
* Plugin version: 2.12.0
* Platform: iOS or Android: Android
* OS version: 8.1
* Device manufacturer / model: Pixel 2
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config
locationAuthorizationRequest: 'Any', 
              debug: false,
              desiredAccuracy: 0,
              distanceFilter: distanceFilter

## Expected Behavior

Plugin works as expected on iOs and Android with no crashes.

## Actual Behavior

In Android, if I create a signed apk through Android Studio and install, I get a crash when starting the background geolocation plugin. I have verified that if I do not start the plugin, there is no issue. 

If I build and deploy from ionic terminal, there is no issue: 
**ionic cordova run android --device**

If I run an unsigned version from Android Studio, there is no issue.

The error I get when I view Android Studio logs is: 

```
05-18 15:52:25.947 14447-14447/? I/zygote64: Deoptimizing java.lang.String com.transistorsoft.locationmanager.logger.c$TSLog$a.a(java.lang.String) due to JIT inline cache
    Deoptimizing java.lang.String com.transistorsoft.locationmanager.logger.a$TSLog$a.c(java.lang.String) due to JIT inline cache
05-18 15:52:25.948 1143-1715/? W/ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{c1f8631 u0 com.myApp.myApp411test/com.transistorsoft.locationmanager.BackgroundGeolocationService}
05-18 15:52:25.959 2466-3030/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.myApp.myApp411test], packageName=null]
05-18 15:52:25.959 1143-1715/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-18 15:52:25.963 14447-14447/? D/AndroidRuntime: Shutting down VM
05-18 15:52:25.963 14447-14447/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myApp.myApp411test, PID: 14447
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by christocracy** [comment]
Are you minimizing your release build (ie using proguard)?

**Comment by jwburnside** [comment]
We have not specifically configured any minimization, and there are no proguard references anywhere in the Android platform project.

**Comment by jwburnside** [comment]
Sure: 

```
this.backgroundGeolocation = (<any>window).BackgroundGeolocation;

this.backgroundGeolocation.on('location', this.onLocation.bind(this));
this.backgroundGeolocation.on('motionchange', this.onMotionChange.bind(this));
this.backgroundGeolocation.on('activitychange', this.onActivityChange.bind(this));
this.backgroundGeolocation.on('geofence', this.onGeofence.bind(this));
this.backgroundGeolocation.on('http', this.onHttpSuccess.bind(this), this.onHttpFailure.bind(this));

let distanceFilter = RuleValueConstants.TNC_MIN_DISTANCE_BETWEEN_USER_LOCATION_UPDATES_METERS_DEFAULT;

this.ruleValueService.findRuleValueWithName(RuleValueConstants.TNC_MIN_DISTANCE_BETWEEN_USER_LOCATION_UPDATES_METERS_NAME)
  .subscribe(ruleValue => {
    distanceFilter = parseInt(ruleValue.value);

    this.backgroundGeolocation.configure({
      locationAuthorizationRequest: 'Any', 
      debug: false,
      desiredAccuracy: 0,
      distanceFilter: distanceFilter,
    }, (state) => {
      this.backgroundGeolocation.start();
    });
  }, err => {
    this.backgroundGeolocation.configure({
      debug: false,
      desiredAccuracy: 0,
      distanceFilter: RuleValueConstants.TNC_MIN_DISTANCE_BETWEEN_USER_LOCATION_UPDATES_METERS_DEFAULT,
    }, (state) => {
      this.backgroundGeolocation.start();
    });
  });
```

**Comment by jwburnside** [comment]
Here's some more detail with logLevel set to 5: 

```
05-22 10:28:56.294 2857-3026/? I/AsyncOpDispatcher: 45-xlb
05-22 10:28:56.458 29485-29628/? V/Diagnostic_Location: Location permission is unauthorized
05-22 10:28:56.459 29485-29628/? V/Diagnostic_Location: Location permission is unauthorized
05-22 10:28:56.476 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 2199 : startGeolocationTracking()
05-22 10:28:56.476 29485-29485/? I/chromium: [INFO:CONSOLE(2199)] "startGeolocationTracking()", source: file:///android_asset/www/build/main.js (2199)
  05-22 10:28:56.478 2857-3026/? I/AsyncOpDispatcher: 45-xlb
05-22 10:28:56.484 29485-29628/? V/Diagnostic: Get authorisation status for android.permission.ACCESS_COARSE_LOCATION
  05-22 10:28:56.485 29485-29628/? V/Diagnostic: Get authorisation status for android.permission.ACCESS_FINE_LOCATION
  05-22 10:28:56.489 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 3967 : status: "NOT_REQUESTED"
05-22 10:28:56.489 29485-29485/? I/chromium: [INFO:CONSOLE(3967)] "status: "NOT_REQUESTED"", source: file:///android_asset/www/build/main.js (3967)
  05-22 10:28:56.489 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 3969 : location service permission has not been requested yet.
05-22 10:28:56.489 29485-29485/? I/chromium: [INFO:CONSOLE(3969)] "location service permission has not been requested yet.", source: file:///android_asset/www/build/main.js (3969)
  05-22 10:28:56.489 29485-29628/? V/Diagnostic: Get authorisation status for android.permission.ACCESS_COARSE_LOCATION
  05-22 10:28:56.490 29485-29628/? V/Diagnostic: Get authorisation status for android.permission.ACCESS_FINE_LOCATION
  05-22 10:28:56.491 29485-29628/? D/Diagnostic: Requesting permission for android.permission.ACCESS_COARSE_LOCATION
  Requesting permission for android.permission.ACCESS_FINE_LOCATION
  05-22 10:28:56.491 29485-29628/? V/Diagnostic: Requesting permissions

--------- beginning of system
05-22 10:28:56.491 1113-11658/? I/ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10341
05-22 10:28:56.492 744-744/? D/QCOM PowerHAL: LAUNCH HINT: ON
05-22 10:28:56.493 744-744/? D/QCOM PowerHAL: Activity launch hint handled
05-22 10:28:56.503 29485-29485/? D/CordovaActivity: Paused the activity.
05-22 10:28:56.554 29485-29628/? W/PluginManager: THREAD WARNING: exec() call to Globalization.getLocaleName blocked the main thread for 22ms. Plugin should use CordovaInterface.getThreadPool().
05-22 10:28:56.568 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 10027 : language en-US
05-22 10:28:56.568 29485-29485/? I/chromium: [INFO:CONSOLE(10027)] "language en-US", source: file:///android_asset/www/build/main.js (10027)
  05-22 10:28:56.583 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 10031 : time zone America/New_York
05-22 10:28:56.583 29485-29485/? I/chromium: [INFO:CONSOLE(10031)] "time zone America/New_York", source: file:///android_asset/www/build/main.js (10031)
  05-22 10:28:56.586 7727-7727/? I/GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
05-22 10:28:56.587 7727-7727/? I/GoogleInputMethod: onStartInput() : Dummy InputConnection bound
05-22 10:28:56.600 1113-1136/? I/ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity: +95ms
05-22 10:28:56.607 744-744/? D/QCOM PowerHAL: LAUNCH HINT: OFF
05-22 10:29:00.697 1113-1113/? I/GnssLocationProvider: WakeLock acquired by sendMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@e978af0)
05-22 10:29:00.697 1113-1126/? I/GnssLocationProvider: WakeLock released by handleMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@e978af0)
05-22 10:29:00.700 1113-1113/? I/GnssLocationProvider: WakeLock acquired by sendMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@87b7869)
05-22 10:29:00.701 1113-1126/? I/GnssLocationProvider: WakeLock released by handleMessage(SET_REQUEST, 0, com.android.server.location.GnssLocationProvider$GpsRequest@87b7869)
05-22 10:29:00.711 1113-11658/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.717 1113-11658/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.718 1113-11660/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.726 29485-29485/? V/Diagnostic: Received result for permissions request id=146627
05-22 10:29:00.727 29485-29485/? V/Diagnostic: Authorisation for ACCESS_COARSE_LOCATION is GRANTED
Authorisation for ACCESS_FINE_LOCATION is GRANTED
05-22 10:29:00.751 1113-11658/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.753 1113-14832/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.755 1113-14830/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.756 29485-29485/? D/CordovaActivity: Resumed the activity.
05-22 10:29:00.768 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 3972 : granted: GRANTED
05-22 10:29:00.768 29485-29485/? I/chromium: [INFO:CONSOLE(3972)] "granted: GRANTED", source: file:///android_asset/www/build/main.js (3972)
  05-22 10:29:00.768 1113-2539/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.768 7727-7727/? I/GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
05-22 10:29:00.769 7727-7727/? I/GoogleInputMethod: onStartInput() : Dummy InputConnection bound
05-22 10:29:00.771 1113-11658/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.773 1113-14832/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.774 1113-2539/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.774 1113-14832/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:00.776 1113-2539/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:00.780 9852-29815/? I/AsyncOpDispatcher: com.google.android.gms.gcm-GcmExportedIntentOperation
05-22 10:29:00.790 9852-9924/? I/Places: Converted 0 out of 0 WiFi scans
05-22 10:29:00.790 1113-11658/? I/WifiService: getConnectionInfo uid=10012
05-22 10:29:00.792 9852-28778/? W/ctxmgr: [AclManager]No 2 for (accnt=account#1897449176#, com.google.android.gms(10012):UserLocationProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 9852). Was: 2 for 1, account#1897449176#
05-22 10:29:00.793 1113-14830/? I/WifiService: getConnectionInfo uid=10012
getConfiguredNetworks uid=10012
05-22 10:29:00.797 9852-29357/? I/GCoreUlr: Successfully inserted 1 locations
05-22 10:29:00.861 29485-29628/? I/TSLocationManager: ╔═════════════════════════════════════════════
║ LICENSE VALIDATION FAILURE
    ╠═════════════════════════════════════════════
╟─ com.myApp.myAppDriver
05-22 10:29:00.861 29485-29628/? D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.SettingsFailureEvent
No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
05-22 10:29:00.915 29485-29490/? I/zygote64: Do partial code cache collection, code=29KB, data=25KB
After code cache collection, code=29KB, data=25KB
Increasing code cache capacity to 128KB
05-22 10:29:00.917 29485-29628/? D/TSLocationManager: $ addLocationListener()
05-22 10:29:00.919 29485-29628/? D/TSLocationManager: $ addMotionChangeListener()
05-22 10:29:00.921 29485-29628/? D/TSLocationManager: $ addActivityChangeListener()
05-22 10:29:00.923 29485-29628/? D/TSLocationManager: $ addGeofenceListener()
05-22 10:29:00.924 29485-29628/? D/TSLocationManager: $ addHttpListener()
05-22 10:29:00.927 2857-3026/? I/AsyncOpDispatcher: 45-xlb
05-22 10:29:00.934 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 2199 : startGeolocationTracking()
05-22 10:29:00.934 29485-29485/? I/chromium: [INFO:CONSOLE(2199)] "startGeolocationTracking()", source: file:///android_asset/www/build/main.js (2199)
  05-22 10:29:00.935 29485-29628/? V/Diagnostic_Location: Location permission is authorized
05-22 10:29:00.951 29485-29628/? D/TSLocationManager: $ addLocationListener()
05-22 10:29:00.952 29485-29628/? D/TSLocationManager: $ addMotionChangeListener()
05-22 10:29:00.953 29485-29628/? D/TSLocationManager: $ addActivityChangeListener()
05-22 10:29:00.955 29485-29628/? D/TSLocationManager: $ addGeofenceListener()
05-22 10:29:00.956 29485-29628/? D/TSLocationManager: $ addHttpListener()
05-22 10:29:00.959 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 10027 : language en-US
05-22 10:29:00.959 29485-29485/? I/chromium: [INFO:CONSOLE(10027)] "language en-US", source: file:///android_asset/www/build/main.js (10027)
  05-22 10:29:00.960 2857-2873/? I/AsyncOpDispatcher: 45-xlb
05-22 10:29:00.963 29485-29485/? D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 10031 : time zone America/New_York
05-22 10:29:00.963 29485-29485/? I/chromium: [INFO:CONSOLE(10031)] "time zone America/New_York", source: file:///android_asset/www/build/main.js (10031)
  05-22 10:29:00.980 29485-29628/? D/TSLocationManager: $ configure()
05-22 10:29:00.994 29485-29628/? D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
05-22 10:29:01.010 29485-29628/? D/TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true
05-22 10:29:01.018 29485-29628/? W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 38ms. Plugin should use CordovaInterface.getThreadPool().
05-22 10:29:01.018 29485-29485/? I/zygote64: Deoptimizing java.lang.String com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$BackgroundGeolocation$24.aa(java.lang.String) due to JIT inline cache
05-22 10:29:01.019 29485-29485/? I/zygote64: Deoptimizing java.lang.String com.transistorsoft.locationmanager.adapter.TSConfig$BackgroundGeolocation$c.c(java.lang.String) due to JIT inline cache
05-22 10:29:01.021 29485-29628/? D/TSLocationManager: $ start()
05-22 10:29:01.023 29485-29628/? D/TSLocationManager: [c.t.locationmanager.util.b a]
ℹ️  LocationAuthorization: Permission granted
05-22 10:29:01.030 29485-29823/? I/TSLocationManager: - Enable: false → true, trackingMode: 1
05-22 10:29:01.038 1113-14832/? W/ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{3292baa u0 com.myApp.myAppDriver/com.transistorsoft.locationmanager.BackgroundGeolocationService}
05-22 10:29:01.039 29485-29628/? D/TSLocationManager: $ configure()
05-22 10:29:01.050 29485-29490/? I/zygote64: Do partial code cache collection, code=56KB, data=38KB
05-22 10:29:01.051 29485-29490/? I/zygote64: After code cache collection, code=44KB, data=34KB
Increasing code cache capacity to 256KB
05-22 10:29:01.062 1113-11660/? I/WifiService: acquireWifiLock uid=10012 lockMode=2
05-22 10:29:01.062 9852-25700/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.myApp.myAppDriver], packageName=null]
05-22 10:29:01.063 1113-11660/? I/WifiService: releaseWifiLock uid=10012
05-22 10:29:01.064 29485-29628/? D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
05-22 10:29:01.067 29485-29485/? D/AndroidRuntime: Shutting down VM


--------- beginning of crash
05-22 10:29:01.067 29485-29485/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myApp.myAppDriver, PID: 29485
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-22 10:29:01.068 1113-14830/? W/ActivityManager:   Force finishing activity com.myApp.myAppDriver/.MainActivity
05-22 10:29:01.071 1113-1128/? I/ActivityManager: Showing crash dialog for package com.myApp.myAppDriver u0
05-22 10:29:01.079 29485-29628/? W/PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.configure blocked the main thread for 40ms. Plugin should use CordovaInterface.getThreadPool().
05-22 10:29:01.083 2857-29828/? I/AsyncOpDispatcher: com.google.android.gms.security__nonwearable-SnetDropBoxIntentOperation
05-22 10:29:01.088 757-801/? D/CHRE: @ 59895.219: -: id 0, otherClientPresent 0, mode 3
05-22 10:29:01.089 29485-29628/? D/TSLocationManager: $ start()
05-22 10:29:01.090 29485-29628/? D/TSLocationManager: [c.t.locationmanager.util.b a]
ℹ️  LocationAuthorization: Permission granted
05-22 10:29:01.099 29485-29823/? I/TSLocationManager: - Enable: false → true, trackingMode: 1
05-22 10:29:01.571 1113-1127/? W/ActivityManager: Activity pause timeout for ActivityRecord{3ab5f77 u0 com.myApp.myAppDriver/.MainActivity t5505 f}
05-22 10:29:01.752 24800-29833/? W/Gmail: Gmail:No valid account details in bundle: empty username, email address and/or host
05-22 10:29:01.811 2857-5716/? I/AsyncOpDispatcher: 5-LoadOwners
05-22 10:29:01.850 757-801/? D/CHRE: @ 59895.984: +: id 0, otherClientPresent 1, mode 3
05-22 10:29:01.901 2857-3026/? I/AsyncOpDispatcher: 5-LoadOwnerCoverPhoto
05-22 10:29:01.909 2857-3026/? I/AsyncOpDispatcher: 5-LoadOwnerCoverPhoto
05-22 10:29:03.123 2857-3026/? I/AsyncOpDispatcher: 45-xlb
05-22 10:29:04.553 1113-1113/? W/WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@351939b
05-22 10:29:04.575 1113-1113/? I/ActivityManager: Killing 25568:com.instagram.android/u0a183 (adj 906): empty #17
05-22 10:29:04.581 1113-1113/? I/ActivityManager: Killing 28403:com.instagram.android:videoplayer/u0a183 (adj 906): empty #18
05-22 10:29:04.582 1113-1129/? W/zygote64: kill(-25568, 9) failed: No such process
05-22 10:29:04.613 764-764/? E/lowmemorykiller: Error writing /proc/28403/oom_score_adj; errno=22
05-22 10:29:04.615 1113-1129/? W/zygote64: kill(-25568, 9) failed: No such process
05-22 10:29:04.615 1113-11660/? W/ActivityManager: Exception when unbinding service com.instagram.android/com.facebook.video.heroplayer.service.HeroService
android.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:764)
at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1508)
at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:2652)
at com.android.server.am.ActiveServices.killServicesLocked(ActiveServices.java:3051)
at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:18048)
at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:5274)
at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:5464)
at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1626)
at android.os.BinderProxy.sendDeathNotice(Binder.java:844)
05-22 10:29:04.625 1113-1129/? W/zygote64: kill(-25568, 9) failed: No such process
05-22 10:29:04.625 1113-1129/? I/zygote64: Successfully killed process cgroup uid 10183 pid 25568 in 43ms
05-22 10:29:04.626 1113-1129/? W/zygote64: kill(-28403, 9) failed: No such process
05-22 10:29:04.668 1113-1129/? W/zygote64: kill(-28403, 9) failed: No such process
05-22 10:29:04.668 1113-1129/? I/zygote64: Successfully killed process cgroup uid 10183 pid 28403 in 42ms
05-22 10:29:11.156 1582-1582/? E/QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
05-22 10:29:11.157 1582-1582/? E/QtiImsExtUtils: isCarrierConfigEnabled bundle is null
05-22 10:29:12.671 1113-1127/? W/ActivityManager: Activity destroy timeout for ActivityRecord{3ab5f77 u0 com.myApp.myAppDriver/.MainActivity t5505 f}






```
