### ISSUE TITLE
Failed to install 'cordova-background-geolocation-lt': Error: Expected plugin to have ID "cordova-plugin-cocoalumberjack" but got "cordova-plugin-background-fetch"

### ISSUE THREAD

**Issue by whosonlocation** [transistorsoft/cordova-background-geolocation-lt#685]
## Your Environment
* Plugin version: 2.12.2
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.1.0 / ios 4.5.4

## Expected Behavior
Install `cordova-background-geolocation-lt` successfully for iOS platform

## Actual Behavior
Error when installing `cordova-background-geolocation-lt` for ios:
> Plugin dependency "cordova-plugin-background-fetch@5.4.1" already fetched, using that version.
> Installing "cordova-plugin-background-fetch" for ios
> Failed to install 'cordova-background-geolocation-lt': Error: Expected plugin to have ID "cordova-plugin-cocoalumberjack" but got "cordova-plugin-background-fetch".
>     at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:215:15)
>     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:199:9
>     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
>     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
>     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
>     at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
> Failed to restore plugin "cordova-background-geolocation-lt" from config.xml. You might need to try adding it again. Error: Error: Expected plugin to have ID "cordova-plugin-cocoalumberjack" but got "cordova-plugin-background-fetch".

## cordova plugins

> com.borismus.webintent 1.1.0 "WebIntent"
> cordova-background-geolocation-lt 2.12.2 "BackgroundGeolocation"
> cordova-plugin-background-fetch 5.4.0 "CDVBackgroundFetch"
> cordova-plugin-camera 2.4.1 "Camera"
> cordova-plugin-compat 1.2.0 "Compat"
> cordova-plugin-dialogs 1.3.4 "Notification"
> cordova-plugin-geolocation 4.0.1 "Geolocation"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by whosonlocation** [comment]
Sorry Chris, I think I have solved the issue by removing `cordova-plugin-background-fetch@5.4.0` from package.json file, and it might be a version conflict issue or something I guess. Thanks anyway.
