### ISSUE TITLE
App Crash on run Android Studio

### ISSUE THREAD

**Issue by mcherubin** [transistorsoft/cordova-background-geolocation-lt#699]
* Plugin version: 2.8.5
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Huawai VNS-L31
* Cordova version: 7.1.0
* Cordova platform version: 6.4.0

When I run the app with Android Studio on my device it crash on startup with this message:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.dyngoapp.app, PID: 30370
                  java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
                      at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                      at java.lang.Class.getDexCacheType(Class.java:2551)
                      at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
                      at java.lang.reflect.Method.getParameterTypes(Method.java:193)
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
                      at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
                      at com.transistorsoft.locationmanager.BootReceiver.onReceive(Unknown Source)
                      at android.app.ActivityThread.handleReceiver(ActivityThread.java:3177)
                      at android.app.ActivityThread.-wrap18(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:156)
                      at android.app.ActivityThread.main(ActivityThread.java:6523)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                   Caused by: java.lang.ClassNotFoundException: com.google.android.gms.location.ActivityRecognitionResult
                      at java.lang.VMClassLoader.findLoadedClass(Native Method)
                      at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
                      at java.lang.Class.getDexCacheType(Class.java:2551) 
                      at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
                      at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163) 
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
                      at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
                      at org.greenrobot.eventbus.EventBus.register(EventBus.java:136) 
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source) 
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source) 
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source) 
                      at com.transistorsoft.locationmanager.BootReceiver.onReceive(Unknown Source) 
                      at android.app.ActivityThread.handleReceiver(ActivityThread.java:3177) 
                      at android.app.ActivityThread.-wrap18(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:156) 
                      at android.app.ActivityThread.main(ActivityThread.java:6523) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
                      at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source) 
                      at com.transistorsoft.locationmanager.BootReceiver.onReceive(Unknown Source) 
                      at android.app.ActivityThread.handleReceiver(ActivityThread.java:3177) 
                      at android.app.ActivityThread.-wrap18(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:156) 
                      at android.app.ActivityThread.main(ActivityThread.java:6523) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.dyngoapp.app-1/base.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dyngoapp.app-1/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)

**Comment by christocracy** [comment]
Why are you using an old version `2.8.5`?

>java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult

This is issue is caused by using an insufficient version of `play-services`, less than the minimum required version `11.2.0`.

You probably have a mess of other plugins all importing different versions of play-services / `com.android.support` libraries.

Post your `platforms/android/project.properties`

**Comment by mcherubin** [comment]
Thanks for your answer. This my project.properties

target=android-26
cordova.gradle.include.1=cordova-background-geolocation-lt/app-build.gradle
cordova.system.library.1=com.android.support:support-v4:24.1.1+
cordova.system.library.2=com.google.android.gms:play-services-analytics:+
cordova.system.library.3=com.google.android.gms:play-services-auth:+
cordova.system.library.4=com.google.android.gms:play-services-identity:+
cordova.system.library.5=com.android.support:support-v4:24.1.1+
cordova.gradle.include.2=cordova-plugin-linkedin/app-LinkedIn.gradle
cordova.system.library.6=com.google.android.gms:play-services-gcm:+
cordova.system.library.7=com.android.support:support-v4:+
android.library.reference.1=CordovaLib
cordova.system.library.8=com.facebook.android:facebook-android-sdk:4.+

**Comment by christocracy** [comment]
As a test, try this:
```diff
cordova.gradle.include.1=cordova-background-geolocation-lt/app-build.gradle
+cordova.system.library.1=com.android.support:support-v4:27.0.0
+cordova.system.library.2=com.google.android.gms:play-services-analytics:11.8.0
+cordova.system.library.3=com.google.android.gms:play-services-auth:11.8.0-
+cordova.system.library.4=com.google.android.gms:play-services-identity:11.8.0
+cordova.system.library.5=com.android.support:support-v4:27.0.0
cordova.gradle.include.2=cordova-plugin-linkedin/app-LinkedIn.gradle
+cordova.system.library.6=com.google.android.gms:play-services-gcm:11.8.0
+cordova.system.library.7=com.android.support:support-v4:27.0.0
android.library.reference.1=CordovaLib
cordova.system.library.8=com.facebook.android:facebook-android-sdk:4.+
```

**Comment by mcherubin** [comment]
With this directive It doesn't crash at startup but when I start BgGeo I get

I/hwaps: JNI_OnLoad
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.DetectedActivity>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
I/art:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(android.content.Context, android.content.Intent) ((null):-1)
I/art:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter() (CDVBackgroundGeolocation.java:994)
I/art:     at void com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager() (CDVBackgroundGeolocation.java:100)
I/art:     at void com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize() (CDVBackgroundGeolocation.java:91)
I/art:     at void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences) (CordovaPlugin.java:58)
I/art:     at org.apache.cordova.CordovaPlugin org.apache.cordova.PluginManager.getPlugin(java.lang.String) (PluginManager.java:171)
I/art:     at void org.apache.cordova.PluginManager.exec(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (PluginManager.java:122)
I/art:     at java.lang.String org.apache.cordova.CordovaBridge.jsExec(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (CordovaBridge.java:57)
I/art:     at java.lang.String org.apache.cordova.engine.SystemExposedJsApi.exec(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (SystemExposedJsApi.java:41)
I/art:     at void org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(long, boolean) (PG:-2)
I/art:     at void org.chromium.base.SystemMessageHandler.handleMessage(android.os.Message) (PG:9)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art:     at void android.os.Looper.loop() (Looper.java:156)
I/art:     at void android.os.HandlerThread.run() (HandlerThread.java:61)
I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.dyngoapp.app-1/base.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dyngoapp.app-1/lib/arm64, /system/lib64, /vendor/lib64, /system/ve
I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(android.content.Context, android.content.Intent) ((null):-1)
I/art:     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter() (CDVBackgroundGeolocation.java:994)
I/art:     at void com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager() (CDVBackgroundGeolocation.java:100)
I/art:     at void com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize() (CDVBackgroundGeolocation.java:91)
I/art:     at void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences) (CordovaPlugin.java:58)
I/art:     at org.apache.cordova.CordovaPlugin org.apache.cordova.PluginManager.getPlugin(java.lang.String) (PluginManager.java:171)
I/art:     at void org.apache.cordova.PluginManager.exec(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (PluginManager.java:122)
I/art:     at java.lang.String org.apache.cordova.CordovaBridge.jsExec(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (CordovaBridge.java:57)
I/art:     at java.lang.String org.apache.cordova.engine.SystemExposedJsApi.exec(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (SystemExposedJsApi.java:41)
I/art:     at void org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(long, boolean) (PG:-2)
I/art:     at void org.chromium.base.SystemMessageHandler.handleMessage(android.os.Message) (PG:9)
I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/art:     at void android.os.Looper.loop() (Looper.java:156)
I/art:     at void android.os.HandlerThread.run() (HandlerThread.java:61)
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
I/art: (Throwable with no stack trace)Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.dyngoapp.app-1/base.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.dyngoapp.app-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.dyngoapp.app-1/lib/arm64, /system/l
I/art: (Throwable with no stack trace)

**Comment by christocracy** [comment]
One of your other plugins is still causing your app to import an insufficient version of play-services.

Remove the following plugin:
1.  `cordova-plugin-linkedin`
