### ISSUE TITLE
Android App Crash: Attempt to invoke interface method 'void com.transistorsoft.locationmanager.data.a.f()' on a null object reference 

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-background-geolocation-lt#703]
## Your Environment
* Plugin version: Paid Plugin
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung

## Debug logs
06-11 18:05:53.511 30230-30230/com.docandtrack.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.docandtrack.app, PID: 30230
                                                                     java.lang.RuntimeException: Unable to stop service com.transistorsoft.locationmanager.BackgroundGeolocationService@6d29594: java.lang.NullPointerException: Attempt to invoke interface method 'void com.transistorsoft.locationmanager.data.a.f()' on a null object reference
                                                                         at android.app.ActivityThread.handleStopService(ActivityThread.java:3788)
                                                                         at android.app.ActivityThread.-wrap30(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.transistorsoft.locationmanager.data.a.f()' on a null object reference
                                                                         at com.transistorsoft.locationmanager.BackgroundGeolocationService.F(Unknown Source)
                                                                         at com.transistorsoft.locationmanager.BackgroundGeolocationService.onDestroy(Unknown Source)
                                                                         at android.app.ActivityThread.handleStopService(ActivityThread.java:3771)
                                                                         at android.app.ActivityThread.-wrap30(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 

##Description of the whole case scanario

I have a paid Cordova background geolocation plugin. And I have a few question about it. The developer before me working on this project has had added many packages/plugins in the app and now its too confusing that how your plugin is working in my app.

In package.json file, he had added

    "com.transistorsoft.cordova.background-geolocation": "https://github.com/transistorsoft/cordova-background-geolocation.git",
   "com.transistorsoft.cordova.background-geolocation-lt": "https://github.com/transistorsoft/cordova-background-geolocation-lt.git”

And similarly, 

inside config.xml
`<plugin name="com.transistorsoft.cordova.background-geolocation" spec="https://github.com/transistorsoft/cordova-background-geolocation.git" />`

But in one of the thread in git issues, I came across Cristocracy commenting, for paid customer, one should not add such line in package.json.

I have the plugin “com.transistorsoft.cordova.background-geolocation” in my plugin folder.

Now the problem I came across was:

Unable to stop service com.transistorsoft.locationmanager.BackgroundGeolocationService@5b4f83d: java.lang.NullPointerException: Attempt to invoke interface method 'void com.transistorsoft.locationmanager.data.a.f()' on a null object reference
       
But I have configured and started  the  module.

this.gps.setConfig({
          desiredAccuracy: 0,
          distanceFilter: 2000,
          disableElasticity: true,
          stopOnTerminate: false,
          url: my url here,
          batchSync: true,
          maxDaysToPersist: 30,
          headers: {
              "Authorization": "Token " + this.auth.token()
          }
      });
      this.gps.start();
So, what is wrong with the plugin or am I missing something.

my plugins installed are:
`com.transistorsoft.cordova.background-geolocation 1.3.0 "BackgroundGeolocation"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-camera 2.2.0-unofficial-1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 1.2.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-networkactivityindicator 0.1.1 "NetworkActivityIndicator"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
docandtrack-image-plugin 1.0 "ImagePicker"
org.apache.cordova.plugin.ActivityIndicator 1.0.3 "Activity Indicator"
`

Any help would be highly appreciated. 

The plugin asks for location always in use permission  iOS device.. but not fetching current location

**Comment by christocracy** [comment]
```
com.transistorsoft.cordova.background-geolocation 1.3.0 "BackgroundGeolocation"
```
This is an *incredibly* old version.  the latest is `2.12.2`.  Upgrade.

**Comment by christocracy** [comment]
And latest `2.12.2` requires latest Cordova 8 / cordova-android@7

**Comment by shrashwin** [comment]
so as my plugin is paid, i use

cordova plugin add cordova-background-geolocation --variable LICENSE=license here


instead of 

cordova plugin add cordova-background-geolocation-lt --variable LICENSE=license here

is that correct?

**Comment by christocracy** [comment]
delete all references to `com.transistorsoft.cordova.background-geolocation` in your config.xml.

**Comment by christocracy** [comment]
Closed for lack of feedback.
