### ISSUE TITLE
Android crash with phonegap-plugin-push

### ISSUE THREAD

**Issue by redspirit** [transistorsoft/cordova-background-geolocation-lt#742]
OS: Xubuntu 16.04
Node: 8.11.1
Cordova: 7.1.0
Platform: android 6.3.0
Plugins:
- cordova-background-geolocation-lt: 2.11.0
- phonegap-plugin-push: 1.11.1

cordova-background-geolocation-lt works well. But I need to use "classic" push-notifications and I added the phonegap-plugin-push. Immediately I build the application (cordova run android), the application is started, but the cordova-background-geolocation-lt does not work anymore ("ready" event is not fired) and after ~30 seconds the app crashes!

Logcat shows this error:

```
FATAL EXCEPTION: main
 Process: com.guardia.partner, PID: 25239
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
 at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
 at java.lang.reflect.Method.getParameterTypes(Method.java:179)
 at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
 at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
 at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
 at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:151)
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:12)
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:962)
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:104)
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
 at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
 at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
 at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
 at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
 at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
 at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
 at org.chromium.base.SystemMessageHandler.handleMessage(PG:9)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:164)
 at android.os.HandlerThread.run(HandlerThread.java:65)

 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.guardia.partner-WJsrzG9diDHCkATLSSFLBA==/base.apk"],nativeLibraryDirectories=[/data/app/com.guardia.partner-WJsrzG9diDHCkATLSSFLBA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 at java.lang.reflect.Executable.getParameterTypesInternal(Native Method) 
 at java.lang.reflect.Method.getParameterTypes(Method.java:179) 
 at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163) 
 at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
 at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
 at org.greenrobot.eventbus.EventBus.register(EventBus.java:136) 
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:151) 
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13) 
 at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:12) 
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:962) 
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:104) 
 at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91) 
 at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58) 
 at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171) 
 at org.apache.cordova.PluginManager.exec(PluginManager.java:122) 
 at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57) 
 at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
 at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
 at org.chromium.base.SystemMessageHandler.handleMessage(PG:9) 
 at android.os.Handler.dispatchMessage(Handler.java:105) 
 at android.os.Looper.loop(Looper.java:164) 
 at android.os.HandlerThread.run(HandlerThread.java:65) 

```
I tried to install different versions of plugins, but this does not help.
Tested on devices with android 8 (Galaxy S8) and android 7.0 (Moto C Plus)

**Comment by christocracy** [comment]
Latest version of `phonegap-plugin-push` is `2.2.3`.  Use latest version.

**Comment by redspirit** [comment]
phonegap-plugin-push ver 2.x used FCM.
I need GCM this is implemented only in ver 1.x

**Comment by christocracy** [comment]
It's unwise to get yourself stuck behind on such a crucial plugin such as `phonegap-plugin-push`.  It causes issues like the one you're having now.

If `phonegap-plugin-push` decided to migrate to FCM ([because GCM is *deprecated*](https://developers.google.com/cloud-messaging/)), don't you think you should to?

![](https://dl.dropboxusercontent.com/s/1bp763tc8p0y322/Screenshot%202018-07-31%2009.48.32.png?dl=1)

**Comment by redspirit** [comment]
Our backend works with GCM...
phonegap-plugin-push 2 works well.
Thanks for the advice

**Comment by christocracy** [comment]
Your background will work with GCM until **April 11, 2019**.  In 8 months, your background is going to be broken.
