### ISSUE TITLE
ready event is not fired.

### ISSUE THREAD

**Issue by madhurakhal** [transistorsoft/cordova-background-geolocation-lt#822]
## Your Environment
* Plugin version: 2.11.0
* Platform:  Android
* OS version: 6.1.0
* Device manufacturer / model: One plus one
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): `Installed platforms:
  android 6.4.0
  ios 4.5.5
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0`

## Expected Behavior
ready event should be fired.

## Actual Behavior
nothing happens.

## My configuration.
```
     var locationService = window.BackgroundGeolocation;
     locationService.on('location', callbackFn);
            locationService.on('error', failureFn);

            locationService.ready({
              // Geolocation config
              desiredAccuracy                     : 0,
              stationaryRadius                    : 10,
              distanceFilter                      : 10,
              disableElasticity                   : false, // <-- [iOS] Default is 'false'.  Set true to disable speed-based distanceFilter elasticity
              minimumActivityRecognitionConfidence: 50,   // 0-100%.  Minimum activity-confidence for a state-change
              locationUpdateInterval              : 10000,
              fastestLocationUpdateInterval       : 10000,
              activityRecognitionInterval         : 10000,
              stopDetectionDelay                  : 10000,  // Wait x minutes to engage stop-detection system
              stopTimeout                         : 10000,  // Wait x miutes to turn off location system after stop-detection
              activityType                        : 'AutomotiveNavigation',
              disableMotionActivityUpdates        : true, // should be false?!?!
              pausesLocationUpdatesAutomatically  : true,

              // Application config
              debug                      : false, // <-- enable this hear sounds for background-geolocation life-cycle.
              forceReloadOnLocationChange: false,  // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a new location is recorded (WARNING: possibly distruptive to user)
              forceReloadOnMotionChange  : false,    // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when device changes stationary-state (stationary->moving or vice-versa) --WARNING: possibly distruptive to user)
              forceReloadOnGeofence      : false,        // <-- [Android] If the user closes the app **while location-tracking is started** , reboot app when a geofence crossing occurs --WARNING: possibly distruptive to user)
              stopOnTerminate            : false,              // <-- [Android] Allow the background-service to run headless when user closes the app.
              startOnBoot                : true,                   // <-- [Android] Auto start background-service in headless mode when device is powered-up.
              preventSuspend             : true,
              heartbeatInterval          : 60,
              foregroundService: true,

              // HTTP / SQLite config
              url             : config.API_ENTRY_POINT + '/locations/',
              method          : 'POST',
              batchSync       : false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
              autoSync        : true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
              maxDaysToPersist: 1,    // <-- Maximum days to persist a location in plugin's SQLite database when HTTP fails
              maxBatchSize    : 30,
              headers         : {
                "Authorization": $http.defaults.headers.common.Authorization
              },
              params          : {
                "user"    : user.id,
                "sendings": sending_ids
              }
            }, function(state) {    // <-- Current state provided to #configure callback
                // 3.  Start tracking
                console.log('BackgroundGeolocation is configured and ready to use');
                if (!state.enabled) {
                  bgGeo.start(function() {
                    console.log('- BackgroundGeolocation tracking started');
                  });
                }

                $rootScope.gpsActive = true;
              });
          }
        });```


And in console locationService object looks like this.
```
{"LOG_LEVEL_OFF":0,"LOG_LEVEL_ERROR":1,"LOG_LEVEL_WARNING":2,"LOG_LEVEL_INFO":3,"LOG_LEVEL_DEBUG":4,"LOG_LEVEL_VERBOSE":5,"DESIRED_ACCURACY_NAVIGATION":-2,"DESIRED_ACCURACY_HIGH":-1,"DESIRED_ACCURACY_MEDIUM":10,"DESIRED_ACCURACY_LOW":100,"DESIRED_ACCURACY_VERY_LOW":1000,"DESIRED_ACCURACY_THREE_KILOMETER":3000,"AUTHORIZATION_STATUS_NOT_DETERMINED":0,"AUTHORIZATION_STATUS_RESTRICTED":1,"AUTHORIZATION_STATUS_DENIED":2,"AUTHORIZATION_STATUS_ALWAYS":3,"AUTHORIZATION_STATUS_WHEN_IN_USE":4,"NOTIFICATION_PRIORITY_DEFAULT":0,"NOTIFICATION_PRIORITY_HIGH":1,"NOTIFICATION_PRIORITY_LOW":-1,"NOTIFICATION_PRIORITY_MAX":2,"NOTIFICATION_PRIORITY_MIN":-2,"ACTIVITY_TYPE_OTHER":1,"ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION":2,"ACTIVITY_TYPE_FITNESS":3,"ACTIVITY_TYPE_OTHER_NAVIGATION":4,"logger":{}}
```

**Comment by murat0** [comment]
Which version of the plugin are you utilising 2.x or 3.x?

**Comment by christocracy** [comment]
Show me `$ adb logcat -s TSLocationManager` of you app booting.

See [Debugging](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Debugging) wiki.

When debugging, the set `reset: true, debug: true`.

Read the docs carefully for the [`#ready`](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#ready) event and why you'll want to use `reset: true` while developing.

**Comment by christocracy** [comment]
@murat0 There is no `3.x` here.

**Comment by madhurakhal** [comment]
``` 11-01 17:40:04.552 26762 26762 D SystemWebChromeClient: file:///android_asset/www/js/services/LocationManager.js: Line 38 : Current sending_ids:
11-01 17:40:04.552 26762 26762 I chromium: [INFO:CONSOLE(38)] "Current sending_ids: ", source: file:///android_asset/www/js/services/LocationManager.js (38)
11-01 17:40:04.552 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.553 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.553 26293 26293 I Finsky  : [1] com.google.android.finsky.scheduler.ae.a(39): Scheduling fallback in 43199998 (absolute: 208841582)
11-01 17:40:04.554 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.555 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.555 26762 26828 W System.err: java.lang.IllegalAccessError: com.google.android.gms.location.ActivityRecognitionResult
11-01 17:40:04.555 26762 26828 W System.err: 	at dalvik.system.DexFile.defineClassNative(Native Method)
11-01 17:40:04.555 26762 26828 W System.err: 	at dalvik.system.DexFile.defineClass(DexFile.java:226)
11-01 17:40:04.556 26762 26828 W System.err: 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
11-01 17:40:04.556 26762 26828 W System.err: 	at dalvik.system.DexPathList.findClass(DexPathList.java:338)
11-01 17:40:04.556 26762 26828 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
11-01 17:40:04.556 26762 26828 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-01 17:40:04.556 26762 26828 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-01 17:40:04.556 26762 26828 W System.err: 	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
11-01 17:40:04.556 26762 26828 W System.err: 	at java.lang.Class.getDexCacheType(Class.java:476)
11-01 17:40:04.556 26762 26828 W System.err: 	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
11-01 17:40:04.556 26762 26828 W System.err: 	at java.lang.reflect.Method.getParameterTypes(Method.java:170)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:962)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:104)
11-01 17:40:04.556 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
11-01 17:40:04.556 26762 26828 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
11-01 17:40:04.556 26762 26828 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
11-01 17:40:04.556 26762 26828 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:323)
11-01 17:40:04.556 26762 26828 W System.err: 	at android.os.Looper.loop(Looper.java:136)
11-01 17:40:04.556 26762 26828 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-01 17:40:04.557 26293 26293 I Finsky  : [1] com.google.android.finsky.scheduler.ae.a(39): Scheduling fallback in 64799998 (absolute: 230441585)
11-01 17:40:04.559 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.560 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.562 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.563 26762 26828 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.ActivityRecognitionResult>
11-01 17:40:04.563 26762 26828 W System.err: java.lang.IllegalAccessError: com.google.android.gms.location.ActivityRecognitionResult
11-01 17:40:04.564 26762 26828 W System.err: 	at dalvik.system.DexFile.defineClassNative(Native Method)
11-01 17:40:04.564 26762 26828 W System.err: 	at dalvik.system.DexFile.defineClass(DexFile.java:226)
11-01 17:40:04.564 26762 26828 W System.err: 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
11-01 17:40:04.564 26762 26828 W System.err: 	at dalvik.system.DexPathList.findClass(DexPathList.java:338)
11-01 17:40:04.564 26762 26828 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
11-01 17:40:04.564 26762 26828 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-01 17:40:04.564 26762 26828 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-01 17:40:04.564 26762 26828 W System.err: 	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
11-01 17:40:04.564 26762 26828 W System.err: 	at java.lang.Class.getDexCacheType(Class.java:476)
11-01 17:40:04.564 26762 26828 W System.err: 	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
11-01 17:40:04.564 26762 26828 W System.err: 	at java.lang.reflect.Method.getParameterTypes(Method.java:170)
11-01 17:40:04.564 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
11-01 17:40:04.565 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
11-01 17:40:04.565 26762 26828 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
11-01 17:40:04.565 26762 26828 W System.err: 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:962)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:104)
11-01 17:40:04.565 26762 26828 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:91)```

**Comment by christocracy** [comment]
This is why you need to monitor the Android logs, **first**.

Post your `platforms/android/project.properties`.

**Comment by madhurakhal** [comment]
```
target=android-26
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-android-support-gradle-release/cargosteps-cordova-android-support-gradle-release.gradle
cordova.gradle.include.2=cordova-plugin-background-fetch/cargosteps-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:11.8.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/cargosteps-build.gradle
cordova.system.library.3=com.android.support:support-v4:27.+
cordova.system.library.4=com.android.support:support-v4:26.+
cordova.system.library.5=com.android.support:appcompat-v7:26.+
cordova.gradle.include.4=phonegap-plugin-barcodescanner/cargosteps-barcodescanner.gradle
cordova.gradle.include.5=phonegap-plugin-push/cargosteps-push.gradle
cordova.system.library.6=com.android.support:support-v13:23+
cordova.system.library.7=com.google.android.gms:play-services-gcm:12+
cordova.system.library.8=me.leolin:ShortcutBadger:1.1.14@aar
```

**Comment by madhurakhal** [comment]
@christocracy Any updates on this problem.

**Comment by madhurakhal** [comment]
@christocracy any updates. Is it due to plugin or something else?

**Comment by christocracy** [comment]
Edit your `platforms/android/project.properties` directly as a test.
```diff
+ cordova.system.library.1=com.google.android.gms:play-services-location:16.0.0
cordova.system.library.2=com.android.support:appcompat-v7:27.0.0
cordova.gradle.include.3=cordova-background-geolocation-lt/cargosteps-build.gradle
cordova.system.library.3=com.android.support:support-v4:27.+
+ cordova.system.library.4=com.android.support:support-v4:27.+
+ cordova.system.library.5=com.android.support:appcompat-v7:27.+
cordova.gradle.include.4=phonegap-plugin-barcodescanner/cargosteps-barcodescanner.gradle
cordova.gradle.include.5=phonegap-plugin-push/cargosteps-push.gradle
+ cordova.system.library.6=com.android.support:support-v13:27+
+ cordova.system.library.7=com.google.android.gms:play-services-gcm:16.0.0
cordova.system.library.8=me.leolin:ShortcutBadger:1.1.14@aar
```

**Comment by christocracy** [comment]
In an android app, all `com.android.support` libs must be aligned.  When you have mixed version `23.+`, `26.+`, `27.+`, you will have problems.
