### ISSUE TITLE
Unable to make GET request in Headless Mode

### ISSUE THREAD

**Issue by esol1** [transistorsoft/cordova-background-geolocation-lt#858]
## Your Environment
* Plugin version: 2.14.2
* Platform: iOS or Android: Android
* Cordova version (cordova -v): 8.1.2
* Cordova platform version (cordova platform ls): Android 7.1.4

## Expected Behavior
Be able to send a simple http GET request

## Actual Behavior
Fails with the following error: 

```
E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1448)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
        at com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask.SendHeadlessRequest(BackgroundGeolocationHeadlessTask.java:55)
        at com.transistorsoft.cordova.bggeo.BackgroundGeolocationHeadlessTask.onHeadlessTask(BackgroundGeolocationHeadlessTask.java:74)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

## Context
Here's what I'm doing:

public class BackgroundGeolocationHeadlessTask {
    &nbsp;&nbsp;&nbsp;private void SendHeadlessRequest(String identifier) {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try {
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;URL url = new URL("https://my.api.com);
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpURLConnection urlConnection = (HttpsURLConnection)url.openConnection();
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;urlConnection.setRequestMethod("GET");
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;urlConnection.setDoOutput(false);
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;urlConnection.setDoInput(true);
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;urlConnection.connect();
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch(IOException e) {}
    }

&nbsp;&nbsp;&nbsp;@Subscribe(threadMode=ThreadMode.MAIN)
    &nbsp;&nbsp;&nbsp;public void onHeadlessTask(HeadlessEvent event) {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String name = event.getName();
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TSLog.logger.debug("\uD83D\uDC80  event: " + event.getName());
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TSLog.logger.debug("- event: " + event.getEvent());
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SendHeadlessRequest("test");
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;}
}

Research online seems to indicate that the class needs to be extended with AsyncTask but that throws other errors.

Making an http request in Headless Mode must be a pretty common need but I cannot find the answer anywhere.

**Comment by christocracy** [comment]
The plugin imports the superior [`okhttp`](http://square.github.io/okhttp/) library as a dependency.

Use it.

**Comment by christocracy** [comment]
Oh, woops.  you are using okhttp.

**Comment by christocracy** [comment]
Anyhow, the specifics of what you do within your headless-task isn't a problem with the plugin.

**Comment by christocracy** [comment]
Your app is complaining that you're doing HTTP on the main thread.  Do it in an `AsyncTask`.

I easily Googled that for you:
https://stackoverflow.com/questions/6343166/how-do-i-fix-android-os-networkonmainthreadexception
