### ISSUE TITLE
Black screen when restarting the app after being killed with the plugin started

### ISSUE THREAD

**Issue by aledel84** [transistorsoft/cordova-background-geolocation-lt#899]
##Environment
* Plugin version: cordova-background-geolocation-lt 2.14.2
* Platform: Android
* OS version: any android version
* Device manufacturer / model: Samsung and Motorola
* Cordova version (`cordova -v`): 8.1.2
* Plugin config 

let config: Config = {
            reset: true,
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR,
            desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            distanceFilter: 10,
            stopOnTerminate: true,
            startOnBoot: false,
            notificationTitle: "Magiis activado",
            notificationText:"Obteniendo ubicación",
            autoSync: true,
            batchSync: false,
            foregroundService: true,
            url: AppSettings.Url + "drivers/"  + this.identityService.userId + "/reportNumericLocation",
            locationTemplate:'{ "latitude":<%= latitude %>, "longitude":<%= longitude %> }',
            params: undefined,
            headers: {
                Authorization: "Bearer " + this.connectionServices.getToken(),
            },
        };

## Expected Behavior
When the app is killed swiped from menu and started again, it's expected to be opend as usual.

## Actual Behavior
When the app is killed swiped from menu and started again, It shows a black screen for several seconds (5-10 s) before the splash screen. After that android shows a popup saying the app is not responding (wait or close the app).

![issue-mensaje espere](https://user-images.githubusercontent.com/5278962/55650143-4afb6100-57bb-11e9-820d-6b4e747138d3.jpg)
![issue-Pantalla negra](https://user-images.githubusercontent.com/5278962/55650144-4afb6100-57bb-11e9-9c1c-7a38ee961fc0.jpg)

## Steps to Reproduce

1. Start the plugin
2. Kill the app from swipe menu
3. Start the app again
4. Wait for the Black screen

## Context
The app has to report location to server every 10m. Typical use.

## Debug logs
- Android: $ adb logcat:

2019-04-05 15:48:15.822 1446-1452/com.magiis.app.driver I/zygote: Thread[3,tid=1452,WaitingInMainSignalCatcherLoop,Thread*=0xed8fbc00,peer=0x13341d18,"Signal Catcher"]: reacting to signal 3
2019-04-05 15:48:16.047 1446-1452/com.magiis.app.driver I/zygote: Wrote stack traces to '[tombstoned]'
2019-04-05 15:48:20.204 1446-1446/com.magiis.app.driver W/System.err: Cordova thread pool did not terminate.
2019-04-05 15:48:20.207 1446-1446/com.magiis.app.driver D/CordovaWebViewImpl: >>> loadUrl(about:blank)
2019-04-05 15:48:20.209 1446-1446/com.magiis.app.driver W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
2019-04-05 15:48:20.231 1446-1446/com.magiis.app.driver D/ViewRootImpl@edb14ba[MainActivity]: dispatchDetachedFromWindow
2019-04-05 15:48:20.231 1446-1446/com.magiis.app.driver D/InputEventReceiver: channel 'ff46f79 com.magiis.app.driver/com.magiis.app.driver.MainActivity (client)' ~ Disposing input event receiver.
2019-04-05 15:48:20.231 1446-1446/com.magiis.app.driver D/InputEventReceiver: channel 'ff46f79 com.magiis.app.driver/com.magiis.app.driver.MainActivity (client)' ~NativeInputEventReceiver.
2019-04-05 15:48:20.234 1446-1446/com.magiis.app.driver D/InputTransport: Input channel destroyed: fd=137
2019-04-05 15:48:20.235 1446-1446/com.magiis.app.driver D/com.marianhello.bgloc.LocationService: Task has been removed
2019-04-05 15:48:20.257 1446-1446/com.magiis.app.driver I/com.marianhello.bgloc.LocationService: Stopping self
2019-04-05 15:48:20.274 1446-1446/com.magiis.app.driver I/com.marianhello.bgloc.LocationService: Destroying LocationService
2019-04-05 15:48:20.287 1446-1446/com.magiis.app.driver I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Destroying DistanceFilterLocationProvider
2019-04-05 15:48:20.363 1446-2330/com.magiis.app.driver V/FA: Inactivity, disconnecting from the service
2019-04-05 15:48:20.396 1446-1446/com.magiis.app.driver I/CordovaLog: Changing log level to DEBUG(3)
2019-04-05 15:48:20.396 1446-1446/com.magiis.app.driver I/CordovaActivity: Apache Cordova native platform version 7.0.0 is starting
2019-04-05 15:48:20.396 1446-1446/com.magiis.app.driver D/CordovaActivity: CordovaActivity.onCreate()
2019-04-05 15:48:20.398 1446-1446/com.magiis.app.driver V/FA: onActivityCreated
2019-04-05 15:48:20.479 1446-1446/com.magiis.app.driver D/SystemWebViewEngine: CordovaWebView is running on device made by: samsung
2019-04-05 15:48:20.490 1446-1446/com.magiis.app.driver D/PluginManager: init()
2019-04-05 15:48:20.491 1446-1446/com.magiis.app.driver D/FCMPlugin: ==> FCMPlugin initialize
2019-04-05 15:48:20.614 1446-1446/com.magiis.app.driver D/InputTransport: Input channel constructed: fd=138
2019-04-05 15:48:20.615 1446-1446/com.magiis.app.driver D/ViewRootImpl@ccce3ac[MainActivity]: setView = DecorView@3a38875[MainActivity] TM=true MM=false
2019-04-05 15:48:20.624 1446-1446/com.magiis.app.driver D/CordovaWebViewImpl: >>> loadUrl(file:///android_asset/www/index.html)
2019-04-05 15:48:20.656 1446-1446/com.magiis.app.driver D/CordovaActivity: Started the activity.
2019-04-05 15:48:20.665 1446-1446/com.magiis.app.driver D/CordovaActivity: Resumed the activity.
2019-04-05 15:48:20.676 1446-1446/com.magiis.app.driver D/InputTransport: Input channel constructed: fd=151
2019-04-05 15:48:20.677 1446-1446/com.magiis.app.driver D/ViewRootImpl@31a9957[MainActivity]: setView = DecorView@d55fc44[MainActivity] TM=true MM=false
2019-04-05 15:48:20.682 1446-1446/com.magiis.app.driver D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[network -31,726350,-60,530112 hAcc=22 et=+8d20h19m41s916ms alt=90.5999984741211 vAcc=4 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=324]}] isMoving=false
2019-04-05 15:48:20.688 1446-2330/com.magiis.app.driver D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=-5736721592384454117, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5736721592384454116}]
2019-04-05 15:48:20.702 1446-1446/com.magiis.app.driver D/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Location change: Location[network -31,726350,-60,530112 hAcc=22 et=+8d20h19m41s916ms alt=90.5999984741211 vAcc=4 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=324]}] isMoving=false
2019-04-05 15:48:20.714 1446-1446/com.magiis.app.driver I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: startMonitoringStationaryRegion: lat=-31.7263504 lon=-60.5301117 acy=17.649
2019-04-05 15:48:20.717 1446-2330/com.magiis.app.driver V/FA: Connecting to remote service
2019-04-05 15:48:20.723 1446-2330/com.magiis.app.driver V/FA: Connection attempt already in progress
2019-04-05 15:48:20.724 1446-2330/com.magiis.app.driver V/FA: Activity resumed, time: 764420003
2019-04-05 15:48:20.751 1446-1446/com.magiis.app.driver D/com.marianhello.bgloc.LocationService: New location BGLocation[network -31,726350,-60,530112 id=null acc=22 t=1554490062577 et=+8d20h19m41s916ms alt=90.5999984741211 {Bundle[mParcelledData.dataSize=324]} locprov=0]
2019-04-05 15:48:20.755 1446-1451/com.magiis.app.driver I/zygote: Do full code cache collection, code=252KB, data=210KB
2019-04-05 15:48:20.756 1446-1451/com.magiis.app.driver I/zygote: After code cache collection, code=245KB, data=179KB
2019-04-05 15:48:20.776 1446-1446/com.magiis.app.driver D/com.marianhello.bgloc.LocationService: Persisted location: BGLocation[network -31,726350,-60,530112 id=146 acc=22 t=1554490062577 et=+8d20h19m41s916ms alt=90.5999984741211 {Bundle[mParcelledData.dataSize=324]} locprov=0]
2019-04-05 15:48:20.795 1446-1446/com.magiis.app.driver W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(SourceFile:306)
        at org.chromium.android_webview.AwContents.a(SourceFile:278)
        at org.chromium.android_webview.AwContents.q(SourceFile:525)
        at agq.loadingStateChanged(SourceFile:161)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SourceFile:9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
2019-04-05 15:48:20.821 1446-1446/com.magiis.app.driver D/ViewRootImpl@ccce3ac[MainActivity]: dispatchAttachedToWindow
2019-04-05 15:48:20.853 1446-1446/com.magiis.app.driver V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2019-04-05 15:48:20.855 1446-1446/com.magiis.app.driver D/ViewRootImpl@ccce3ac[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3311923200} changed=true
2019-04-05 15:48:20.866 1446-1624/com.magiis.app.driver D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
2019-04-05 15:48:20.866 1446-1624/com.magiis.app.driver D/OpenGLRenderer: eglCreateWindowSurface = 0xed89e2e0, 0xc567f008
2019-04-05 15:48:20.934 1446-1446/com.magiis.app.driver D/ViewRootImpl@31a9957[MainActivity]: dispatchAttachedToWindow
2019-04-05 15:48:20.956 1446-1446/com.magiis.app.driver V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
2019-04-05 15:48:20.957 1446-1446/com.magiis.app.driver D/ViewRootImpl@31a9957[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3311925248} changed=true
2019-04-05 15:48:20.973 1446-1624/com.magiis.app.driver D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
2019-04-05 15:48:20.973 1446-1624/com.magiis.app.driver D/OpenGLRenderer: eglCreateWindowSurface = 0xcaeaa658, 0xc567f808
2019-04-05 15:48:20.990 1446-1446/com.magiis.app.driver D/CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
2019-04-05 15:48:21.003 1446-1446/com.magiis.app.driver D/ViewRootImpl@ccce3ac[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
2019-04-05 15:48:21.052 1446-1446/com.magiis.app.driver D/ViewRootImpl@31a9957[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
2019-04-05 15:48:21.055 1446-2330/com.magiis.app.driver D/FA: Connected to remote service
2019-04-05 15:48:21.059 1446-2330/com.magiis.app.driver V/FA: Processing queued up service tasks: 2
2019-04-05 15:48:21.170 1446-1446/com.magiis.app.driver D/JsMessageQueue: Set native->JS mode to EvalBridgeMode
2019-04-05 15:48:22.360 1446-1677/com.magiis.app.driver D/FCMPlugin: ==> FCMPlugin execute: ready
2019-04-05 15:48:22.365 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js: Line 5 : FCMPlugin.js: is created
2019-04-05 15:48:22.365 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(5)] "FCMPlugin.js: is created", source: file:///android_asset/www/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js (5)
2019-04-05 15:48:22.381 1446-1677/com.magiis.app.driver I/LaunchNavigator: pluginInitialize()
2019-04-05 15:48:22.474 1446-1677/com.magiis.app.driver D/NetworkManager: toLower : wifi
2019-04-05 15:48:22.474 1446-1677/com.magiis.app.driver D/NetworkManager: wifi : wifi
2019-04-05 15:48:22.474 1446-1677/com.magiis.app.driver D/NetworkManager: Connection Type: wifi
2019-04-05 15:48:22.474 1446-1677/com.magiis.app.driver D/NetworkManager: Connection Extra Info: "WorkOffice"
2019-04-05 15:48:22.475 1446-1446/com.magiis.app.driver D/NetworkManager: toLower : wifi
2019-04-05 15:48:22.475 1446-1446/com.magiis.app.driver D/NetworkManager: wifi : wifi
2019-04-05 15:48:22.475 1446-1446/com.magiis.app.driver D/NetworkManager: Connection Type: wifi
2019-04-05 15:48:22.475 1446-1446/com.magiis.app.driver D/NetworkManager: Connection Extra Info: "WorkOffice"
2019-04-05 15:48:22.486 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js: Line 41 : FCMPlugin Ready OK
2019-04-05 15:48:22.486 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(41)] "FCMPlugin Ready OK", source: file:///android_asset/www/plugins/cordova-plugin-fcm-with-dependecy-updated/www/FCMPlugin.js (41)
2019-04-05 15:48:22.508 1446-1446/com.magiis.app.driver D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
2019-04-05 15:48:22.518 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 1 : Ionic Native: deviceready event fired after 580 ms
2019-04-05 15:48:22.518 1446-1677/com.magiis.app.driver I/App: WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
2019-04-05 15:48:22.518 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "Ionic Native: deviceready event fired after 580 ms", source: file:///android_asset/www/build/vendor.js (1)
2019-04-05 15:48:22.567 1446-1677/com.magiis.app.driver W/AudioManager: Use of stream types is deprecated for operations other than volume control
2019-04-05 15:48:22.567 1446-1677/com.magiis.app.driver W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2019-04-05 15:48:22.573 1446-1677/com.magiis.app.driver D/AudioManager: requestAudioFocus status : 1
2019-04-05 15:48:22.573 1446-1677/com.magiis.app.driver D/NativeAudio: Plugin Called: preloadSimple
2019-04-05 15:48:22.574 1446-1677/com.magiis.app.driver D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager$1255dfcom.rjfun.cordova.plugin.nativeaudio.NativeAudio$772b22c
2019-04-05 15:48:22.586 1446-1446/com.magiis.app.driver D/ViewRootImpl@31a9957[MainActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 3311925248} changed=false
2019-04-05 15:48:22.637 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/vendor.js: Line 1 : ERROR
2019-04-05 15:48:22.638 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "ERROR", source: file:///android_asset/www/build/vendor.js (1)
2019-04-05 15:48:22.723 1446-1619/com.magiis.app.driver D/FirebaseInstanceId: topic sync succeeded
2019-04-05 15:48:22.787 1446-1677/com.magiis.app.driver D/NativeAudio: Plugin Called: preloadSimple
2019-04-05 15:48:22.791 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : getAdvancedCurrentPosition 
2019-04-05 15:48:22.791 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "getAdvancedCurrentPosition ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.795 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Initialized
2019-04-05 15:48:22.797 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Action = start
2019-04-05 15:48:22.798 1446-1677/com.magiis.app.driver D/GeolocationPlugin: prefs: action, start
2019-04-05 15:48:22.802 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Execute args: [{"minTime":5000,"minDistance":10,"noWarn":true,"providers":"some","useCache":true,"satelliteData":false,"buffer":false,"bufferSize":0,"signalStrength":false}]
2019-04-05 15:48:22.802 1446-1677/com.magiis.app.driver D/GeolocationPlugin: validatePermissions()
2019-04-05 15:48:22.804 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Counter: 0, display rationale? false
2019-04-05 15:48:22.804 1446-1677/com.magiis.app.driver D/GeolocationPlugin: rationale 4: application startup - no perms are set yet
2019-04-05 15:48:22.809 1446-2366/com.magiis.app.driver D/GeolocationPlugin: Starting LocationManager.NETWORK_PROVIDER
2019-04-05 15:48:22.809 1446-2365/com.magiis.app.driver I/GeolocationPlugin: Available location providers: [passive, gps, network]
2019-04-05 15:48:22.810 1446-2365/com.magiis.app.driver D/GeolocationPlugin: Starting LocationManager.GPS_PROVIDER
2019-04-05 15:48:22.811 1446-1677/com.magiis.app.driver D/FCMPlugin: ==> FCMPlugin execute: getToken
2019-04-05 15:48:22.813 1446-1677/com.magiis.app.driver D/FCMPlugin: ==> FCMPlugin execute: registerNotification
2019-04-05 15:48:22.815 1446-1446/com.magiis.app.driver D/FCMPlugin: 	Token: fr7tkeHv_Lw:APA91bH0ylQ8QxBkq8Nbe8O4q0DwtlRX_nyy5gzhK2AyyBV8-9EzE39V0ZqIi1r1sTjoBAO9dxUwLYIlKdCZ20oU5ccHNq7BOD1t28P9KgBXZQYxUpA5BSCsPwS6e7x7tFBYAuLn4kPx
2019-04-05 15:48:22.861 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : Error al cargar el audio
2019-04-05 15:48:22.862 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "Error al cargar el audio", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.870 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : getAdvancedCurrentPosition response
2019-04-05 15:48:22.870 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "getAdvancedCurrentPosition response", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.871 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : network 
2019-04-05 15:48:22.871 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "network ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.873 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : latitude 
2019-04-05 15:48:22.873 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "latitude ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.874 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : longitude 
2019-04-05 15:48:22.875 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "longitude ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.876 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : location 
2019-04-05 15:48:22.876 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "location ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.878 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : getAdvancedCurrentPosition response
2019-04-05 15:48:22.878 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "getAdvancedCurrentPosition response", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.879 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : gps 
2019-04-05 15:48:22.880 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "gps ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.881 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : latitude 
2019-04-05 15:48:22.881 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "latitude ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.882 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : longitude 
2019-04-05 15:48:22.883 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "longitude ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.884 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : location 
2019-04-05 15:48:22.884 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "location ", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.886 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : getCurrentPosition place (Android)
2019-04-05 15:48:22.886 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "getCurrentPosition place (Android)", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.887 1446-1446/com.magiis.app.driver D/SystemWebChromeClient: file:///android_asset/www/build/1.js: Line 1 : getCurrentPositionCallback
2019-04-05 15:48:22.888 1446-1446/com.magiis.app.driver I/chromium: [INFO:CONSOLE(1)] "getCurrentPositionCallback", source: file:///android_asset/www/build/1.js (1)
2019-04-05 15:48:22.907 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Action = stop
2019-04-05 15:48:22.907 1446-1677/com.magiis.app.driver D/GeolocationPlugin: prefs: action, stop
2019-04-05 15:48:22.908 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Execute args: []
2019-04-05 15:48:22.908 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Attempting to stop gps geolocation
2019-04-05 15:48:22.914 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Stopping network geolocation
2019-04-05 15:48:22.915 1446-1677/com.magiis.app.driver D/GeolocationPlugin: Stopping geolocation

**Comment by christocracy** [comment]
Show me your:
```
$ cordova plugins
```

**Comment by aledel84** [comment]
com-badrit-base64 0.2.0 "Base64"
cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-geolocation 1.6.2 "Cordova Advanced Geolocation Plugin - Android"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-fcm-with-dependecy-updated 2.2.4 "Cordova FCM Push Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.2 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"

**Comment by christocracy** [comment]
Your error log above references the Mauron85 fork.
```
2019-04-05 15:48:20.751 1446-1446/com.magiis.app.driver D/com.marianhello.bgloc.LocationService: New location BGLocation[network 
```

Also, how many geolocation plugins do you have installed??  The only one you need is mine.  Get rid of everything else.

**Comment by aledel84** [comment]
OMG! Mauron85 is a kind of virus. I've uninstalled it so many times. I'll review this and I'll see what happend. Thanks.

**Comment by christocracy** [comment]
When in doubt, destroy and re-add the platform:
```
$ cordova platform remove android
$ cordova platform add android
```

**Comment by aledel84** [comment]
cordova-plugin-geolocation is not needed right?

**Comment by christocracy** [comment]
`cordova-background-geolocation` is all you need.

**Comment by aledel84** [comment]
Done! The plugin causing trouble was **cordova-plugin-advanced-geolocation** I uninstalled it and everything's working excellent now.
We already bought the plugin. Thanks!

Issue solved.
