### ISSUE TITLE
AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by PerryRylance** [transistorsoft/cordova-background-geolocation-lt#908]
This happens immediately after calling BackgroundGeolocation.start()

````04-17 14:26:13.516 22519 22519 E AndroidRuntime: Process: com.CodeCabin.WPGoogleMapsApp, PID: 22519
04-17 14:26:13.516 22519 22519 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b5e5ce2 u0 com.CodeCabin.WPGoogleMapsApp/com.transistorsoft.locationmanager.BackgroundGeolocationService}
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6981)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-17 14:26:13.516 22519 22519 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)```

## Your Environment
* Plugin version: 3.0.0-beta.3
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung SM-G960F
* Cordova version 8.1.2
* Cordova platform version android 7.1.4
* Plugin config

`{
		reset: true,
		
		enableHighAccuracy: true,
		desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
		distanceFilter: 10,     // Record a location every 10 meters.
		
		// heartbeatInterval: 60,  // <-- heartbeat event every 60s
		
		stopTimeout: 1,         // Change state to stationary after 1 min with device "still"
		startOnBoot: true,
		stopOnTerminate: false, // Don't stop tracking when app is terminated.
		foregroundService: true,// Prevent Android from terminating service due to memory pressure from other apps.
		
		url: this.getBackgroundGeolocationURL(),
		params: this.getRequestParams(),
		autoSync: true         // Auto sync each recorded location to #url immediately.
		
	};`

## Expected Behavior
When we call `start`, the geolocation should start

## Actual Behavior
When we call `start`, the app crashes (release only)

## Steps to Reproduce
<!--- reproduce this issue; include code to reproduce, if relevant -->
1. Build for release
2. Either launch the app from the command line, or download from Google Play
3. Run the app, the background service is ready (checked in debug)
4. Call BackgroundGeolocation.start()

## Context
Just start recording

## Debug logs
See above

**Comment by christocracy** [comment]
You're using an old `3.0.0-beta`.   See [CHANGELOG](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/CHANGELOG.md#change-log)

**Comment by christocracy** [comment]
And have you purchased a license?  The Android plugin works only in `DEBUG` builds without purchasing a license (so you can try before you buy).

**Comment by PerryRylance** [comment]
Yes we have, thank you for the prompt response. I'll try updating our plugin version now

**Comment by christocracy** [comment]
Why are you posting to the public repo instead of the [private customers only repo](https://github.com/transistorsoft/cordova-background-geolocation)?

(if it's 404, talk to the person who registered the product:  ask them to login to Product Dashboard and  click `[+ Add Member]` button.)

**Comment by christocracy** [comment]
And also note that the license key changed for `3.0.0-rc.+`.  Ask your product owner to get you the new `3.0.0` license key from the Dashboard.

**Comment by PerryRylance** [comment]
Only my CEO has access to that - I'm just a humble technician

Updating the plugin didn't help. I have requested the new style keys, thanks again
