### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;

### ISSUE THREAD

**Issue by matejkramny** [transistorsoft/cordova-background-geolocation-lt#966]
## Your Environment
* Plugin version: 3.0.8
* Platform: Android
* OS version: 9
* Device manufacturer / model: pixel 3a
* Cordova version (`cordova -v`): 9.0.0 (lib 9.0.1)
* Cordova platform version (`cordova platform ls`):
```
Installed platforms:
  android 8.0.0
```
* Plugin config provided to `#ready`: not relevant

## Expected Behavior
Plugin should be working

## Actual Behavior
Runtime exception (below). Doesn't crash the app but location tracking isn't working as expected.

```
System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/ActivityTransitionEvent;
07-27 19:09:58.534 11164 11253 W System.err: 	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
07-27 19:09:58.534 11164 11253 W System.err: 	at java.lang.reflect.Method.getParameterTypes(Method.java:186)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:157)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:17)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.getAdapter(CDVBackgroundGeolocation.java:1051)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.initializeLocationManager(CDVBackgroundGeolocation.java:118)
07-27 19:09:58.534 11164 11253 W System.err: 	at com.transistorsoft.cordova.bggeo.CDVBackgroundGeolocation.pluginInitialize(CDVBackgroundGeolocation.java:101)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-27 19:09:58.534 11164 11253 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-27 19:09:58.534 11164 11253 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
07-27 19:09:58.534 11164 11253 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:326)
07-27 19:09:58.534 11164 11253 W System.err: 	at android.os.Looper.loop(Looper.java:160)
07-27 19:09:58.534 11164 11253 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
07-27 19:09:58.535 11164 11253 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.ActivityTransitionEvent" on path: DexPathList[[zip file "/data/app/com.example.anonymous-wyBeERm4bNcAYLFcKsD53A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.anonymous-wyBeERm4bNcAYLFcKsD53A==/lib/arm64, /data/app/com.example.anonymous-wyBeERm4bNcAYLFcKsD53A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
07-27 19:09:58.535 11164 11253 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-27 19:09:58.535 11164 11253 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-27 19:09:58.535 11164 11253 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

## Context
Happens after starting app

## Plugins

```

call-number 0.0.2 "Cordova Call Number Plugin"
cordova-background-geolocation-lt 3.0.8 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.5.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm-with-dependecy-updated 2.4.0 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

## android/project.properties

```
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/travelapp-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:10.+
cordova.system.library.2=com.android.support:appcompat-v7:27.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:1.3.0-2
cordova.gradle.include.2=cordova-background-geolocation-lt/travelapp-build.gradle
cordova.system.library.8=com.google.firebase:firebase-core:10.+
cordova.system.library.9=com.google.firebase:firebase-messaging:10.+
cordova.gradle.include.3=cordova-plugin-fcm-with-dependecy-updated/travelapp-FCMPlugin.gradle
cordova.system.library.10=com.android.support:support-annotations:27.+
cordova.system.library.11=com.android.support:support-v4:24.1.1+
```

I have a feeling it might be to do with `cordova-plugin-fcm-with-dependecy-updated`. The library has been locked to google library `v10.+`.

The docs suggestion min version v26, but this seems nothing to do with the firebase dep.

Any ideas /pointers welcome.

Many thanks

**Comment by christocracy** [comment]
You’re using an insufficient version of play-services:location.  You can’t pin to v10.+, it’s far too old, by at least 2 years.

Post your platforms/android/project.properties

**Comment by matejkramny** [comment]
Hey Chris, it't in the last sections above

**Comment by christocracy** [comment]
Sorry, I see you posted project.properties

**Comment by matejkramny** [comment]
Is it this one? `com.android.support:support-v4:24.1.1+` - should this be v26+?

**Comment by christocracy** [comment]
First of all, when you see this:  `target=android-28`, all your `com.android.support` libs should have their major version aligned to `28.x.x`.

**Comment by christocracy** [comment]
```
try this:
```diff
+cordova.system.library.1=com.google.android.gms:play-services-location:16.0.0
+cordova.system.library.8=com.google.firebase:firebase-core:17.0.1
+cordova.system.library.9=com.google.firebase:firebase-messaging:19.0.1
```

**Comment by christocracy** [comment]
browse http://maven.google.com to see all google api versions.

**Comment by matejkramny** [comment]
Cheers, going to try that and report.

**Comment by matejkramny** [comment]
Thank you Chris, it's due to the firebase repo.

Going to use this, it seems most up to date if anyone has this issue again: https://github.com/dpa99c/cordova-plugin-firebasex
